### ISSUE TITLE
error in building locally

### ISSUE THREAD

**Issue by nileshgulia1** [collective/gatsby-source-plone#10]
After executing `cd tests/gatsby-starter-default && gatsby develop` throws error like:
```
error UNHANDLED REJECTION


  Error: Unable to find plugin "gatsby-source-plone"

  - load-plugins.js:96 resolvePlugin
    [gatsby-starter-default]/[gatsby]/dist/bootstrap/load-plugins.js:96:11

  - load-plugins.js:147 processPlugin
    [gatsby-starter-default]/[gatsby]/dist/bootstrap/load-plugins.js:147:27

  - load-plugins.js:168
    [gatsby-starter-default]/[gatsby]/dist/bootstrap/load-plugins.js:168:28

  - Array.forEach

  - load-plugins.js:167 _callee$
    [gatsby-starter-default]/[gatsby]/dist/bootstrap/load-plugins.js:167:28

  - index.js:122 _callee$
    [gatsby-starter-default]/[gatsby]/dist/bootstrap/index.js:122:20

  - next_tick.js:131 _combinedTickCallback
    internal/process/next_tick.js:131:7
```
After running `cd tests/gatsby-starter-default && gatsby serve` error is:
`specified directory "public" doesn't exist!`
I have python 2.7 node 8.9.4, and nodejs 6.11.4 installed still it throws error. Also `bin/instance fg` not working. @cekk can you help me?

**Comment by tisto** [comment]
@nileshgulia1 did you run "npm install"? Are you sure you are using Node 8.9.4? What does "node -v" return on the command line?

**Comment by nileshgulia1** [comment]
@tisto  running node -v shows v8.9.4 .I also have python 2.17.13 installed with virtualenv.

**Comment by tulikavijay** [comment]
@nileshgulia1 can you write the steps you followed?
Also for me, if i used npm or yarn to install some packages , it would show the same error.

**Comment by nileshgulia1** [comment]
@tulikavijay  I have used npm to install packages and use `gatspy develop` to start the development build and got stuck at this error.

**Comment by tulikavijay** [comment]
I think instaling packages through npm is creating the error. You don't need to install packages. 
Maybe give it a try again...

**Comment by nileshgulia1** [comment]
@tulikavijay I removed node_modules folder and tried again it now shows 
```
error gatsby <develop> can only be run for a gatsby site.
Either the current working directory does not contain a package.json or 'gatsby' is not specified as a dependency
```
>Either the current working directory does not contain a package.json

It contains package.json and i also have gatsby-cli installed.

**Comment by tulikavijay** [comment]
@nileshgulia1 is your local dev running?

**Comment by nileshgulia1** [comment]
Yes, This should be closed now.Thanks
