### ISSUE TITLE
Transform (parse) rich text fields HTML into react nodes with gatsby links and images

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-source-plone#103]
* only links within the current base url should be transformed to gatsby-link
* links outside the domain of the base url should be normal links
* links above the current base url but within the current domain should be transformed into spans (without link) because they lead nowhere
* images with known source should be transformed to gatsby-images
* images with relative link above the curren base url in the same domain should be dropped (because they could show nothing)

**Comment by datakurre** [comment]
@ajayns Let's continue the discussion about rich text transform under this issue.

The goal is to make it as easy as possible to have fixed rich text in gatsby site project. Therefore as much of the code and dependencies as possible should be in the plugin.

This would be easiest to do in the plugin, but then the issues is that graphql can only transmit HTML as string for the site project.

We could wrap everything into a RichText-component, but then we would do a lot of processing for each rich text page, possibly in browser. Also dynamically checking availability of each found link from available graphql may not be easy. In addition, we should somehow configure the component with our source base url, which sounds wrong.

Instead, let's still try to do this all in plugin, but then use  https://github.com/pravdomil/react-serialize to serialize the parsed react tree into a string for the gatsby-site. We could then provide a simple component which does deserialization of that in gatsby site project.

**Comment by datakurre** [comment]
@ajayns To simplify this more, as this is getting experimental

* [ ] try to do react-html-parser step in the plugin; because the plugin know our source baseUrl and has the available nodes in an easy structure, replacing links with gatsby-links might be easiest there

* [ ] let's then try react-serialize to turn that react tree into string to be available for gatsby site

* [ ] let's try react-serialize for deserializing that in our starter demo project (requires to add react-serialize as dependenc)

**Comment by datakurre** [comment]
It might be that we end up with a pretty complex story where:

* the plugin parses HTML, founds all replaceable links and images with matching page / image / file
* the plugin replaces those matches with our custom Link and Image components for links and images
* the resulting React tree is serialized with some 3rd party library
* in a gatsby site project that serialized tree is deserialized with our custom RichText component
* when the site is rendered, our custom components work as wrappers for Gatsby Link and Image so that e.g. sharped images can be used

So we will need to iterate on this to find solution. Hopefully we find one, because this would be great feature.

**Comment by datakurre** [comment]
@ajayns I've been looking into getting images (and also files) linked with HTML transform. It is a bit complicated, because we don't know anything about their publicURL or sharp resolution URLs in our plugin. AFAIK, those can only be fetched with GraphQL in gatsby site project.

I have a WIP code where

* plugin collects or links, images, etc found in HTML transform and injects them as a new `_backlinks` attribute into linked nodes

* then in default template, there is an extra query against `_backlinks` to get all images that are linked from the current document

* document component gets all those images with document and could use a custom Img component to replace deserialized Img-components with resolution-filled gatsby image

So, I'll probably finish this and you could move forward.

With those in place, eg. a Document component could get

**Comment by datakurre** [comment]
Btw, I wonder if it is just incompleteness of GatsbyJS v2 that I need to use gatsby-source-filesystem v2 to get response from createRemoteFileNode. v2-version of the plugin returns just null.

**Comment by ajayns** [comment]
@datakurre I didn't get what you meant? We need to import createRemoteFileNode from gatsby-source-filesystem and it needs to be present in gatsby-site as well, configured with plugin options to expose publicURL fields, I didn't get what you meant by v2 returns null

**Comment by datakurre** [comment]
@ajayns 

on

```js
      if (node.image) {
        try {
          imageNode = await createRemoteFileNode({
            url: node.image.download,
            store,
            cache,
            createNode: createImageNode,
          });
        } catch (e) {
          console.error('Error creating image file nodes: ', e);
        }
      }
```
`imageNode` is null with `"gatsby-source-filesystem": "next"`, but works with the latest version from 1.x-series.

**Comment by ajayns** [comment]
Yes, I can see the same thing happening when source-filesystem is v2 for the createRemoteFileNode import. I can't seem to find any docs in migration or plugin docs about any issues or so, maybe we should open an issue in the Gatsby repo?

**Comment by ajayns** [comment]
@datakurre As, I also encountered this issue, I thought it'd be a good idea to compare the different versions of the plugin and check out the changes, that may not have been documented yet. And so I ran into this: https://github.com/gatsbyjs/gatsby/issues/6351#issuecomment-403621291

Could that be relevant for us? I'm still discussing with the Gatsby community on this

**Comment by datakurre** [comment]
Yes. I tried to pass createNodeId, but was still unable to get it work. Old version works, so let’s wait for docs.

**Comment by KyleAMathews** [comment]
Hey, any way I can help? There's a number of other plugins that have upgraded to v2 that use createRemoteFileNode and I'm not aware of any breaking changes other than the createNodeId change.

**Comment by ajayns** [comment]
@KyleAMathews It could be the wrapper createNode functions we use? I don't see any other change that we've made as compared to the normal usage:
https://github.com/collective/gatsby-source-plone/blob/90fa199533422e1511a9a09e095c5050becae80c/src/gatsby-node.js#L157-L213

Anything to add @datakurre

**Comment by KyleAMathews** [comment]
Yeah, you should create the unwrapped `createNode` action to it.

https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-filesystem#createremotefilenode

**Comment by KyleAMathews** [comment]
Looking at it, I don't think anything else has changed. When you were testing the v2 upgrade, did you set all gatsby package versions to `next`?

**Comment by datakurre** [comment]
@KyleAMathews Thank you. I'll double check everything, try with `createNodeId`again and report the results.

**Comment by datakurre** [comment]
@KyleAMathews @ajayns Thank you for your input. I believe that our issue was that our `createNode`-wrappers were not async (in addition to missing `createNodeId`argument).
