### ISSUE TITLE
Get Type Schema and handle file nodes

### ISSUE THREAD

**Issue by ajayns** [collective/gatsby-source-plone#104]
Discussion started here: #95 

Reference: https://plonerestapi.readthedocs.io/en/latest/types.html

**Comment by ajayns** [comment]
@datakurre , so what you mean by this (correct me if I'm wrong), is that, we get the schema of each node type beforehand and process it's image/file Node if present based on this schema?

**Comment by datakurre** [comment]
@ajayns Yes. The same applies for transforming RichTextField HTML https://github.com/collective/gatsby-source-plone/issues/103 and possibly dropping collection query data https://github.com/collective/gatsby-source-plone/issues/20. 

Even the basic content types are configurable: it's possible to take image off from News Item and add Image into regular document.

In the long run, I'd also expect that we need to have options later to configure custom processor for custom field types.

**Comment by ajayns** [comment]
What would be a good enough condition to check if a content type has files/images? I'm thinking of this:

```
{
  "fieldsets": [
    {
      "fields": [
        "title", 
        "description", 
        "text", 
        "changeNote"
      ], 
      "id": "default", 
      "title": "Default"
    }, 
```
**fieldsets[0].fields should contain 'file' or 'image'**

And based on this, on the processing file nodes module, we'll take up the content type and handle files/images as per the data we received processing the schema.

**Comment by cekk** [comment]
that snipped is taken from the restapi's schema call?
i think that for each field you should also have a "widget" property..or not?

**Comment by ajayns** [comment]
Yes, I forgot to mention, updated now. @cekk 
Also, in the `properties` attribute, `widget` is defined for some of the children attributes. How is this useful to us?

**Comment by cekk** [comment]
I don't see the update, but each field has a type and a widget property.

A widget is how the field is rendered in the form. For example an image or a file have the file selector widget, the title have a text widget (I don't remember the names).

You could use these two props to handle file and image fields

**Comment by ajayns** [comment]
I've updated it now with the whole schema and also mentioned which endpoint I used. @cekk 

As per the schema I got from the API, doesn't seem like we can use the widget property. I think we can handle both images and files the same way while processing, and handle them accordingly in the tester?

**Comment by datakurre** [comment]
`➜ curl -H "Accept: application/json" -H "Authorization: Bearer ..." "https://.../en/@types/File"|jq ".properties.file"`

```json
{
  "description": "",
  "properties": {
    "file.contentType": {
      "default": "",
      "description": "The content type identifies the type of data.",
      "title": "Content Type",
      "type": "string"
    },
    "file.data": {
      "default": "",
      "description": "The actual content of the object.",
      "title": "Data",
      "type": "string"
    },
    "file.filename": {
      "description": "",
      "title": "Filename",
      "type": "string"
    }
  },
  "title": "File",
  "type": "object"
}
```

`➜ curl -H "Accept: application/json" -H "Authorization: Bearer ..." "https://.../en/@types/Image"|jq ".properties.image"`

```json
{
  "description": "",
  "properties": {
    "image.contentType": {
      "default": "",
      "description": "The content type identifies the type of data.",
      "title": "Content Type",
      "type": "string"
    },
    "image.data": {
      "default": "",
      "description": "The actual content of the object.",
      "title": "Data",
      "type": "string"
    },
    "image.filename": {
      "description": "",
      "title": "Filename",
      "type": "string"
    }
  },
  "title": "Image",
  "type": "object"
}
```

`➜ curl -H "Accept: application/json" -H "Authorization: Bearer ..." "https://.../en/@types/News%20Item"|jq ".properties.image"`

```json
{
  "description": "",
  "properties": {
    "image.contentType": {
      "default": "",
      "description": "The content type identifies the type of data.",
      "title": "Content Type",
      "type": "string"
    },
    "image.data": {
      "default": "",
      "description": "The actual content of the object.",
      "title": "Data",
      "type": "string"
    },
    "image.filename": {
      "description": "",
      "title": "Filename",
      "type": "string"
    }
  },
  "title": "Lead Image",
  "type": "object"
}
```

`➜ curl -H "Accept: application/json" -H "Authorization: Bearer ..." "https://.../en/@types/Document"|jq ".properties.text"`


```json
{
  "description": "",
  "title": "Text",
  "type": "string",
  "widget": "richtext"
}
```

`➜ curl -H "Accept: application/json" -H "Authorization: Bearer ..." "https://.../en/@types/Collection"|jq ".properties.query"`


```json
{
  "additionalItems": true,
  "description": "Define the search terms for the items you want to list by choosing what to match on. The list of results will be dynamically updated",
  "items": {
    "description": "",
    "key_type": {
      "additional": {},
      "schema": {
        "description": "",
        "title": "",
        "type": "string"
      }
    },
    "title": "",
    "type": "dict",
    "value_type": {
      "additional": {},
      "schema": {
        "description": "",
        "title": "",
        "type": "string"
      }
    }
  },
  "title": "Search terms",
  "type": "array",
  "uniqueItems": false
}
```

**Comment by datakurre** [comment]
It seems there is no obvious solution, but some case per case heuristics are needed to figure out whether a field is e.g. image, file, collection query or rich text (with possibly HTML as value).

**Comment by datakurre** [comment]
File and Image can be detected with combination of "type": "object" and some keys in properties. Other are less clear.

**Comment by cekk** [comment]
Some widgets don't expose "widget" attribute.
In Beethoven sprint me and @thet fixed reference field widget to expose that attribute. We could do the same for file and image widgets too, if needed

**Comment by datakurre** [comment]
Widget is configurable, so it is not complete solution.

**Comment by ajayns** [comment]
Talking about the case of files for now, the process I've thought of is:
1. Fetch schema of all the types in the `@types` endpoint, process this info and find out which all content types have images or files in it (or both maybe?)
2. When process nodes, functions for handling images and files are used as per the information about each type we got in 1

But we're still discussing on how we can determine if a content type has files/images or not yes?

**Comment by datakurre** [comment]
@ajayns File and Image can be detected with combination of "type": "object" and file/image-prefixed names in properties.

**Comment by ajayns** [comment]
@datakurre `fieldsets[0].fields` contains `image` or `file` is not a valid indicator?

**Comment by datakurre** [comment]
No. It just a field name. It could be anything on custom types.

**Comment by ajayns** [comment]
Oh alright, got it, let me play around and try come up with an implementation.

**Comment by ajayns** [comment]
I've tried out a basic approach in my fork in branch `schema`. What I realized while doing so is that some of the types seem to be giving a 500 error from the Plone rest.api.

For instance, I noted that `http://localhost:8080/Plone/@types/Event` gives:
```
{
    "message": "datetime.datetime(2018, 6, 28, 17, 0, tzinfo=<UTC>) is not JSON serializable",
    "traceback": [
        "File \"/plone/lib/python2.7/site-packages/ZPublisher/Publish.py\", line 138, in publish",
        "    request, bind=1)",
        "",
        "  File \"/plone/lib/python2.7/site-packages/ZPublisher/mapply.py\", line 77, in mapply",
        "    if debug is not None: return debug(object,args,context)",
        "",
        "  File \"/plone/lib/python2.7/site-packages/ZPublisher/Publish.py\", line 48, in call_object",
        "    result=apply(object,args) # Type s<cr> to step into published object.",
        "",
        "  File \"/plone/lib/python2.7/site-packages/plone/rest/service.py\", line 23, in __call__",
        "    return self.render()",
        "",
        "  File \"/plone/lib/python2.7/site-packages/plone/restapi/services/__init__.py\", line 22, in render",
        "    return json.dumps(content, indent=2, sort_keys=True)",
        "",
        "  File \"/usr/local/lib/python2.7/json/__init__.py\", line 251, in dumps",
        "    sort_keys=sort_keys, **kw).encode(obj)",
        "",
        "  File \"/usr/local/lib/python2.7/json/encoder.py\", line 209, in encode",
        "    chunks = list(chunks)",
        "",
        "  File \"/usr/local/lib/python2.7/json/encoder.py\", line 434, in _iterencode",
        "    for chunk in _iterencode_dict(o, _current_indent_level):",
        "",
        "  File \"/usr/local/lib/python2.7/json/encoder.py\", line 408, in _iterencode_dict",
        "    for chunk in chunks:",
        "",
        "  File \"/usr/local/lib/python2.7/json/encoder.py\", line 408, in _iterencode_dict",
        "    for chunk in chunks:",
        "",
        "  File \"/usr/local/lib/python2.7/json/encoder.py\", line 408, in _iterencode_dict",
        "    for chunk in chunks:",
        "",
        "  File \"/usr/local/lib/python2.7/json/encoder.py\", line 442, in _iterencode",
        "    o = _default(o)",
        "",
        "  File \"/usr/local/lib/python2.7/json/encoder.py\", line 184, in default",
        "    raise TypeError(repr(o) + \" is not JSON serializable\")"
    ],
    "type": "TypeError"
}
```

**Comment by cekk** [comment]
Nice..this seems a restapi error.
Try to see if it's an already solved problem in later releases, or we need to open a new issue

**Comment by ajayns** [comment]
Looks like it's mentioned here: https://github.com/plone/plone.restapi/issues/190 Not exactly the same, but similar. No action had been taken though

**Comment by datakurre** [comment]
@ajayns Take this as a change to implement some error handling while you are implementing the logic to detect image field from News Item.

Sooner or later a REST API call from our plugin to Plone will fail. Then there are two options: either the plugin could log the error and continue, or fail hard. Possibly this could be an option.

I also noticed that types endpoint requires authenticated user. Not a big issue now, but at some point it might be good to be able to sideload type schemas form filesystem to allow also anonymous use.

**Comment by datakurre** [comment]
I opened an issue https://github.com/plone/plone.restapi/issues/574

**Comment by datakurre** [comment]
@ajayns I looked into plone.restapi code and for me it looks like a generic fix there is not trivial. So, we need to be able to get over broken types endpoint call.

Ugly thing is that we will need to know to transform rich text field in event.

@ajayns Radical solution would be to abandon this approach and try to deduct the field types from the content JSON. We know that all images, files and rich text fields have very specific structure in content object JSON export.

**Comment by datakurre** [comment]
The again, also mixed solution is possible. We use schema for those types it is available and field data for the rest.

Schema driven approach is better, because it is faster than checking every field value. But we need alternative solution, because fixing restapi might take time. And would only land into restapi 3.x.

**Comment by cekk** [comment]
I agree.
As usually we could start "easy" using the Infos from content JSON and proceed with the implementation.
Then, when the project is finished and restapi fixed that issue, we could reimplement this stuff with schema infos

**Comment by ajayns** [comment]
I went through all of this and while thinking of an approach, I couldn't figure out what'd be the best way to do the checking using content. Unsure if taking the schema from just a few types would be a good approach, even for now. 

This is a rough idea I got while going through the response data:
We're checking for specific types to handle remote files right now (namely Image and News Item), so instead of this check, we could check if the node has a field `image` or in the case of files, field `file`. Then do the needful processing based on this check on each nodes. 

Opinions @cekk @datakurre ?

**Comment by datakurre** [comment]
I agree. Schemas were not as useful as I expected.

@ajayns Your last proposal is a good start. Begin with that and we generalize it later.

**Comment by datakurre** [comment]
Let's leave this open once these have been fixed:

* [ ] https://github.com/collective/gatsby-source-plone/issues/103 (HTML text fields)
* [ ] https://github.com/collective/gatsby-source-plone/issues/20 (query fields)

**Comment by ajayns** [comment]
What's a good way of detecting HTML attributes from the response data? I've seen that all `text` attributes with a `content-type: 'text/html'`, has a `data` attribute with HTML as a string.

**Comment by cekk** [comment]
text/html content-type could be what you need.

IMO graphql should return the unparsed string. You can use react-html-parser when you need to render the page. I don't think that we could store some jsx data into graphql nodes.

but i agree with @datakurre about #103 : when you create the node, you should parse/fix links and images. I don't know how much easy this could be.

**Comment by ajayns** [comment]
Yes, I was thinking the same. 
So correct me if I'm wrong, we need to add `react-html-parser` in the gatsby-starter-default tester project to prevent the use of `dangerouslySetInnerHTML` and in the plugin figure out a method to handle links and image srcs from the HTML string.

**Comment by datakurre** [comment]
@ajayns Could be wrap that logic into a React component, e.g. `<RichText/>`so that the component is provided by the plugin and only the plugin need to depend on react-html -parser?

**Comment by ajayns** [comment]
@datakurre That does sound look a good approach but I'm unsure on how to handle the packaging. 
From my experience working with npm packages, I think we'll have an index.js that exports this component. Plus, adding a React component into the plugin would also mean we need to update the Babel setup.

**Comment by datakurre** [comment]
@ajayns Let's continue at https://github.com/collective/gatsby-source-plone/issues/103

I have some ideas there.

**Comment by ajayns** [comment]
Since we've handled image and file nodes, and we have a separate issue for the HTML parsing feature, plus we're not using the schema approach at all, would it be a good idea to close this issue? For the RichText component, could open a new issue then

**Comment by datakurre** [comment]
As conclusion for this: we decided to detect image, file and richtext field directly from the data, because schema information was too ambiquos.
