### ISSUE TITLE
How to handle date values?

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-source-plone#105]
What is the proper way to handle date(time) values in Gatsby? Should they be parsed into Date objects when in source plugin?

**Comment by ajayns** [comment]
I haven't seen any documentation in Gatsby itself regarding this, also haven't specifically seen it in other source-plugins. I'll do a bit more research and see. Perhaps, we have the freedom to decide as per our requirements.

**Comment by datakurre** [comment]
Date formatting is implicitly supported and works with date(time)s provided by plone OOTB https://www.gatsbyjs.org/docs/graphql-reference/#format

**Comment by ajayns** [comment]
Oh yes, that's very handy! We can use it while improving on the gatsby starter
