### ISSUE TITLE
Plugin doesn't fetch from from restapi unless Basic Auth provided

### ISSUE THREAD

**Issue by ajayns** [collective/gatsby-source-plone#11]
When trying to retrieve contents from `http://localhost:8080/Plone/@search` an Error 401 (unauthorized) is encountered unless Basic Auth is provided with the axios headers. 

I'm using the version of Node specified and a Plone 5.1 instance running with Plone.restapi.

**Comment by ajayns** [comment]
@tisto any idea on what is wrong?

**Comment by tisto** [comment]
@ajayns the @search endpoint should work without any auth. Can you please provide a full curl example against plonedemo.kitconcept.com? This might be a plone.restapi issue...

**Comment by ajayns** [comment]
@tisto There seem to be no issue when using curl on plonedemo.kitconcept.com.
` curl -i https://plonedemo.kitconcept.com/en/@search -H 'Accept: application/json' `
This returns the json data for every item without providing auth.

But when I run it against my local deployment of Plone, it seems to ask for auth:
`curl -i http://localhost:8080/Plone/@search -H 'Accept: application/json'`

Gives:
```
HTTP/1.1 401 Unauthorized
Server: Zope/(2.13.26, python 2.7.12, linux2) ZServer/1.1
Date: Sat, 24 Feb 2018 12:02:17 GMT
Bobo-Exception-Line: 27
Content-Length: 94
Bobo-Exception-Value: See the server error log for details
Bobo-Exception-File: __init__.py
Bobo-Exception-Type: <class 'zExceptions.unauthorized.Unauthorized'>
X-Frame-Options: SAMEORIGIN
Content-Type: application/json

{
  "message": "Missing 'plone.restapi: Use REST API' permission", 
  "type": "Unauthorized"
}
```
I'm running a local instance of Plone 5.1, and NOTE: _this seems to ask for permissions for all of the restapi endpoints._

Is it an issue with my local deployment?

**Comment by tisto** [comment]
@ajayns it seems you used an old version of plone.restapi and did not run an upgrade step. Either create a new Plone instance from the scratch with the latest version or go to the Add-ons controlpanel and run the plone.restapi upgrade step.

**Comment by ajayns** [comment]
@tisto Yes, it seemed to be a local issue which is fixed now. Thanks!
