### ISSUE TITLE
Narrative documentation (and revisiting documentation)

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-source-plone#112]
Currently we have made documentation per feature.

After we have enough features (rich text transforms, collections, client-side searchable index), the documentation should be revisited and narration built around it.

Paul Roeland (polyester) should be requested for reviewing this documentation.

**Comment by ajayns** [comment]
What exactly do you mean by narrative documentation? Something along the lines of explaining every feature in a sequential manner that includes tutorials?

**Comment by datakurre** [comment]
@ajayns Yes. It should be enough for the user to find the documentation for gatsby-source-plone and by get a new gatsby site built by following that.

Of course we should link a lot to GatsbyJS-documentation whenever possible.

Possibly this should be aligned with gatsby-starter-plone.

**Comment by ajayns** [comment]
I've was thinking of a flow for the narrative documentation and this is what I came up with:
* Introduction, beginner content, links to all docs/repos
* Starter installation, run starter
* Illustrate basic querying by getting children in root folder
* Page creation:
  - gatsby-node.js config
  - default template
  - components for different data types
  - breadcrumbs for basic navigation
* Handling images using Sharp
* Handling files
* RichText component:
  - Configuration, explanation
  - Usage
* Navbar navigation

This flow would let users know on how to work with the plugin properly (hopefully I haven't missed anything) but what I'm confused about is what all the gatsby-starter-plone should include. If it already has the code for page creation, RichText, Navigation etc, we just have to link to it showing this code works like this. But that'd mean the user won't be configuring it himself using the narrative documention, if we want that to happen, we probably have to remove a few features in starter (that may not be common to all Plone sites) and let user add using the documentation as per his requirement

**Comment by datakurre** [comment]
@polyester I recall you volunteered to represent ”stakeholder” for this Gatsby GSOC project. Any thoughts for documentation?

**Comment by ajayns** [comment]
@cekk This could also come relevant to your proposed Gatsby training!

**Comment by polyester** [comment]
I would find it no problem that the user does not get to _configure_ a site using the narrative documentation, but is guided along an already-configured one.

What's more important is that the user ends up with a **working**, complete gatsby site, with all features. It is much easier for users to then start playing around by _disabling_ stuff they don't need, and tailoring it to their needs. So, ideally it should contain all the goodness of the [test/default]. (https://github.com/collective/gatsby-source-plone/tree/master/tests/gatsby-starter-default) . 

Of course, that depends on the user having a Plone site available, and it might be too much to expect them to run Docker commands and pull in a complete Plone site. 

Maybe it's an idea to have the current fixture/test-Plone running as a demo site somewhere? With a public URL.

Or have the gatsby-starter-plone build a gatsby site from already-available demo sites, like http://demo.plone.de/en _(I don't think it has a collection, but it has some demo content at least)._ And provide the parts that this (or another) demo-Plone site doesn't have in the starter kit as well, but comment it out.

I hope I'm making sense here; I think it's nice to have the narrative documentation work along a fully-featured (even if some parts commented out) gatsby-starter-plone that gives the user an actual, working example. If it pulls content live from an over-the-internet demo site that adds more "wow" factor.

**Comment by ajayns** [comment]
I agree with @polyester here, a fully functional starter with all/most of the features implemented would really be pretty cool, with an as minimal setup as possible (an online Plone site would be a great idea). This resolves the question if the starter should have the features implemented. 

@datakurre What's your idea about the online Plone site we can use as the source?

**Comment by datakurre** [comment]
@polyester @tkimnguyen @sneridagh Would it be possible for plone.org to have restapi with anonymous access enabled?

**Comment by datakurre** [comment]
@ajayns Alternative to real live site could be a docker setup from our plugin example. You could start with reusing the import/export code from the example. Later I could set a separate repo from them so that we would have automatically updated, populated image, at docke hub.

**Comment by polyester** [comment]
I think we can have either plone.org with restapi enabled, or talk @pbauer  into equipping demo.plone.de (which will soon be demo.plone.org) with restapi.

I'm in favor of using a real live site, because maybe for @datakurre and other developer-type people it is completely natural and low-barrier to have Docker running on your laptop, it is a hurdle for other people. Ideally, one would not have to do that just for following a tutorial and be amazed by the gatsby-starter.

**Comment by ajayns** [comment]
Also, on adding this documentation, I'm thinking of a folder inside `/docs` named 'Generating a static site from Plone site' and having multiple files for each step like:
```
1_setting-up-site.md
2_basic-querying.md
...and so on
```

**Comment by datakurre** [comment]
@polyester @tkimnguyen Who is responsible for maintaining plone.org buildout? Does adding restapi require board decision? Any chance we could get this before end of GSOC?

**Comment by ajayns** [comment]
It'd be great if we can do it as soon as possible then, I'll currently start and layout plans and code with the local docker image and start working on the docs as well.

**Comment by ajayns** [comment]
While writing up on the narrative docs, I realized it'd be a good idea to link to existing docs, for instance, while using a feature in the tutorial, can link to this specific feature's docs for more info. So what would be a good approach for this? The options would be the github md file, else we have the hosted gatsby example site which includes all the docs.

**Comment by cekk** [comment]
GitHub page for me

**Comment by ajayns** [comment]
For illustration, the two ways are (taking the case of authentication docs):
1. https://github.com/collective/gatsby-source-plone/blob/master/docs/authentication.md
2. https://collective.github.io/gatsby-source-plone/docs/authentication/

**Comment by cekk** [comment]
I mean GitHub.io page, so the second option ;)

**Comment by ajayns** [comment]
Hey @datakurre @cekk I believe I have the narrative docs in order for the basic setup, covering all features of the starter with the latest PR!

**Comment by datakurre** [comment]
https://collective.github.io/gatsby-source-plone/tutorial/
