### ISSUE TITLE
error UNHANDLED EXCEPTION

### ISSUE THREAD

**Issue by ajayns** [collective/gatsby-source-plone#13]
Running `gatsby develop` in the `tests/gatsby-starter-default` seems to be giving an error which seems to be caused by NodeJS watching too many files. 

The issue is same as: https://github.com/gatsbyjs/gatsby/issues/3395
And I found the temporary fix: https://stackoverflow.com/questions/22475849/node-js-error-enospc

Is there a permanent fix for this? It seems to be a NodeJS error, but is there anyway we can tweak the project to prevent this issue? Also, any exact clarification on why it's happening just for this project, cause I haven't encountered this issue before?

@tisto @cekk @sneridagh Any help would be greatly appreciated!

**Comment by tisto** [comment]
@ajayns this is really more an OS issue than a Gatsby / Node problem. A permanent fix is possible but highly depends on the OS you are using. Not sure if that really fits into gatsby-source-plone.

**Comment by tisto** [comment]
FYI: I removed the bug label because this has nothing to do with gatsby-source-plone IMHO.

**Comment by ajayns** [comment]
It doesn't seem to be happening for rest of the Gatsby projects I've worked on, which is why I mentioned it here. If it's not an issue with this repo, I'll close it? @tisto

**Comment by tisto** [comment]
Strange. Can you please paste the full error trace here? Please always include all steps to reproduce with detailed information about your OS/npm version etc together will a full error trace.

**Comment by ajayns** [comment]
Seems to be caused by either node or OS configs.
OS: Ubuntu 16.04
Node: 8.9.0
npm: 5.6.0

I'll close it cause the issue seems to no longer appearing and I can't seem to reproduce it. @tisto
