### ISSUE TITLE
Gatsby mediaType is fixed to text/html

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-source-plone#130]
when for files and images it should be read from the REST API data

```
  let node = {
    internal: {
      contentDigest: createContentDigest(data),
      mediaType: 'text/html',
    },
  };
```

**Comment by datakurre** [comment]
"Each source plugin is responsible for setting the media type for the nodes they create. This way, source and transformer plugins can work together easily."

**Comment by ajayns** [comment]
From going through the restapi data the best way that seems plausible here is:
* For images and files set `mediaType` from `image['content-type']` and `file['content-type']` respectively
* For rest of the nodes, default it to `text/html`

**Comment by ajayns** [comment]
But don't some NewsItem objects and such have an image field but it's still a NewsItem? In that case wouldn't it be a bad idea to set `mediaType` as some image media type?

**Comment by datakurre** [comment]
Good point. Because any Plone object might contain HTML, text/html might actually be good for all.

Let’s fix this just with a comment on why it is text/html. We do handle actual images and files separately, so they get all transforma properly.
