### ISSUE TITLE
Testing with a real Plone site

### ISSUE THREAD

**Issue by ajayns** [collective/gatsby-source-plone#133]
@cekk Do mention any issues you have here! I'm also checking out each feature implemented.

This would help us do any minor fixes and be ready to use the plugin with our proposed gatsby-starter-plone.

**Comment by cekk** [comment]
i tried to import data from a small plone site (415 items in catalog), and it seems to work very well with the recursion-mode.
The import doesn't take too much and the contents seems to have the correct data.

I have some problems with the pages created from the starter. I'll open some separated issues for this.

**Comment by cekk** [comment]
ok, the only problem in the starter, is that [here](https://github.com/collective/gatsby-source-plone/blob/master/tests/gatsby-starter-default/src/pages/index.js#L10) I don't have anything (i don't have a docs folder, so the query returns nothing).

Commenting that line, everything works.
Also breadcrumbs and site actions are ok.
Internal links works
Files are served correctly

**Comment by ajayns** [comment]
Yes currently, the starter is configured to use it's own docs as a source. So here, at the index page, the plugin displays docs/index.md. This is not an error but it's cause of the specific config we have for the gatsby-site for our use.

**Comment by datakurre** [comment]
That was to be expected.

@KyleAMathews Would you be able to give us some generic tips on how to optimize source plugin memory usage?

**Comment by datakurre** [comment]
As we delegate file nodes to gatsby-source-filesystem, I wonder, how could it be that blobs still way memory? Just JSON should not take that much...

**Comment by ajayns** [comment]
I haven't much explored optimization and handling such huge sites yet, I'll do some research and get back.

cc @m-allanson @pieh insights appreciated

**Comment by pieh** [comment]
This might be something we currently are actually working on (but might not be) - see https://github.com/gatsbyjs/gatsby/issues/6611 and https://github.com/gatsbyjs/gatsby/issues/6656

Nodes itself aren't taking *that* much memory - but serialization is problematic when there is a lot of nodes. There were some fixes recently published already, so try updating gatsby to beta-55

**Comment by datakurre** [comment]
@pieh Thanks for the update.

@cekk @ajayns I believe that for now it's good enough for us to acknowledge that with large amount of nodes, memory issues are expected, and target for smaller sites instead, until it is sure that gatsby itself should scale.

Until that, instead of optimizing too early, we probably should look into using gatsby cache https://github.com/collective/gatsby-source-plone/issues/136 to make updating sites with 1-10k pages practical.

**Comment by cekk** [comment]
@datakurre i agree.
Mine was only a "stress test".
An ideal site candidate is more like the first one.

Do we need more tests or can close this issue?

**Comment by datakurre** [comment]
@cekk It was a great stress test and found real issues.

Let's close this and run more tests once we have the starter. I hope to have implemented caching support by then.
