### ISSUE TITLE
Should we drop BFS-traverse?

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-source-plone#134]
I do like that we tried both search-endpoint and bfg-traverse for fetching data to gatsby.

Initially I thought that BFS would be superior, but now that I've been playing more with gatsby myself, I may have changed my mind.

My concern is related to the need to control pages that are published through gatsby. Currently, with logged-in account it would be very easy to leak private pages from Plone into gatsby data. With search endpoint it would be easy to search only for public pages.

I need to do a little more research related to my ideas, but I'm getting ready to admit that I was wrong about recursive approach.

**Comment by ajayns** [comment]
But we do need to think about efficiency for huge Plone sites as well right? And users wouldn't be happy sitting at it stuck at `source and transform nodes` for a long while.

**Comment by datakurre** [comment]
@ajayns I probably was wrong also on that, because search makes it easier to limit included data, and also the included site depth. The current BFS code looks simpler than the search code, but if we had any options to it (like limit the depth), it would get as complex or more complex than search.

What I didn't know prior the search implementation was how easy it was to connect parent nodes with their children. I was expecting that to be much more difficult, making BFS superior.

Obviously this is something that is beyond GSOC. Trying the plugin with real data probably helps to decide something on this topic.

**Comment by cekk** [comment]
I agree with @datakurre..with search we can limit results with some simple options. We can handle this also with bfs but with more checks in Gatsby code. The search approach handle this thing natively.

About efficiency: I don't know if this is a real issue, because could be normal to wait "some time" to staticize a website. A 400 pages website took me few minutes on my old laptop. I need to try with a bigger website in the next days

**Comment by datakurre** [comment]
I assume there’s a way (or simo be) to speed up subsequent builds by saving fetch date into plugin status and only fetching changed content (and deleting removed).

**Comment by ajayns** [comment]
@datakurre Hmm your points do make sense. 

And yes, if the 400 pages took a few minutes I guess that's pretty fine for now for efficiency.
