### ISSUE TITLE
Complement missing schemas using setFieldsOnGraphQLNodeType

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-source-plone#135]
Replaces and fixes #76 

Gatsby API hook "setFieldsOnGraphQLNodeType" is called once for every GraphQL node type after they have been resolved. Implementing that hook in plugin we could intercept all Plone-types, fetch their schema information from Plone and add missing fields.

Not trivial, because data from Plone schema endpoint is far from perfect.

**Comment by cekk** [comment]
So we don't need to add some fake contents?
This hook is the one that creates also graphql queries for different portal_types?

**Comment by datakurre** [comment]
@cekk Yes and no.

I assume we don't need fake contents. Haven't tested this yet. But it needs to be documented that reading portal types requires credentials (not available for build without secret). So, without credentials fake content may be required.

All graphql queries are created in the gatsby site project. The source plugin only makes nodes available and searchable. The gatsby site project decides what to query.

**Comment by datakurre** [comment]
Replaced by https://github.com/collective/gatsby-source-plone/issues/168
