### ISSUE TITLE
Add support for gatsbyjs cache

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-source-plone#136]
I've been trying to understand gatsby build cache. My current understanding is that there is now magic in it, but each plugin could use the cache as they wish.

For big sites cache could use a lot of disk, so our plugin cache usage should probably be optional, but maybe still on by default?

In the beginning of "sourceNodes", the plugin should save the current timestamp.

The plugin could cache all REST API calls by their URL and then on subsequent build try cache lookup before retrieving from Plone.

The plugin should look for the previous "setPluginStatus" timestamp from gatsby redux store and search for changes from Plone after that timestamp (and remove removed nodes - nodes missing from updated folders).

Before returning "sourceNodes" the plugin should "setPluginStatus" with the current timestamp.

**Comment by KyleAMathews** [comment]
Yeah, this is correct. All nodes are automatically persisted between runs. Source plugins can take advantage of this cache by only fetching what's changed since the last run which is obviously far faster.

**Comment by datakurre** [comment]
@KyleAMathews Thanks.

@ajayns @cekk This is is probably simpler than I thought. Initially I didn't think that gatsby caches nodes and uses cache implicitly...

So, it's probably enought that

* plugin uses setPluginStatus to save timestamp before the first fetch

* when previous source plugin timestamp is found from gatsby store state, the plugin only does search for changes and then calls createNode or deleteNode for proper delta

**Comment by KyleAMathews** [comment]
You also need to "touch" nodes that aren't updated or deleted as otherwise they'll be garbage collected.

**Comment by datakurre** [comment]
@KyleAMathews Ok.

So, no need to call deleteNode, after all.

@ajayns @cekk So, if we need to go through every node id any way to touch them, instead of playing with timestamp, it might be easier to: cache list of all seen nodes at the end of the build, and then on following builds, get the list from cache, go through all search results, but only fetch data for those not in the ”seen” list (and touch those that are). That is even easier that any option in above.

**Comment by datakurre** [comment]
@KyleAMathews Would you be able to confirm these finding on supporting Gatsby build cache?

* in addition to call `touchNode` to keep cached nodes from being garbage collected, we also need to call `deleteNode` for removed nodes to actually remove the nodes and related pages from build (we usually generate page for each node)

* when an existing parent with children has been changed and we update the node with `createNode`, we need to reconnect cached children with `createParentChildLink` (otherwise we get errors on build)

With these in place we seem to be able to use cache as expected with minimal time spent for `source and transform nodes`.

For `deleteNode` we need to know all the cached nodes to be able to delete the disappeared ones. We could use `getNodes` and match the owner, but I wonder if it is better to let the plugin save Set of node ids it owns into its state. Opinions?

**Comment by datakurre** [comment]
Or maybe, source plugin should always first call "touchNode" for all still available nodes to avoid them from being garbage collected during "createNode". Never thought about that, but that is what eg. gatsby-source-contentful does...

**Comment by datakurre** [comment]
@ajayns @cekk Cache support is more tricky than I expected. Our REST API provides us breadcrumbs and navigation components, but those are very prone to indirect changes. E.g. updating a single parent title, requires updating the whole subtree to get updated breadcrumbs. The same applies for navigation, except updating navigation may require updating the whole subtree of the parent of the changed page...

Proably we need to make "Components" their own gatsby types so that we can update them independently (components can be rendered without rendering the content objects).

**Comment by datakurre** [comment]
@ajayns @cekk I found my way around ”createNode deleting all child nodes” issue, but since I’m only working on this occasionally, I need one more week.

I propose to drop support for ”expansions”. I would replace them with built-in support for breadcrumbs and navigation as their own gatsby node types (PloneNavigationComponent, PloneBreadcrumbsComponent). I would continue to fetch them by default also into content node attributes so that it would not be breaking change. Cache support, on the other hand, would only support indirect updates for those components.

So, for cache support, a change to some Plone page would

- update that page node and its parent node
- update breadcrumbs for that page node and possible subtree
- updste navigation for parent’s subtree (parent and its recursive children)

All this is mandatory to make the source plugin usable in real life where we want as fast build as possible after every change.

I will update the example in this project and provide pull for the starter.

**Comment by KyleAMathews** [comment]
Curious what parent/child relationships you're creating? We haven't done a great job at communicating when these should be used. Essentially they're just for "transformer" plugins. The reason we delete child nodes when you delete a parent is that if you delete a file node that is also transformed into a markdown node, the markdown node needs deleted or else it could stick around.

If the relationship between nodes isn't a origin/transformed relationship, then you should just create relationships using `___NODE`. This _can_ still create problems e.g. you link to a node then then is deleted — you need to make sure you clean up the now broken links — but then nodes are only deleted if they were actually deleted upstream.

@pieh wrote up a summary of this here: https://github.com/gatsbyjs/gatsby/issues/4537

**Comment by calcsam** [comment]
I've written up more documentation for how creating relationships works. Not merged yet, but here's the documentation.

https://github.com/gatsbyjs/gatsby/blob/f142bc592fe255ed68011023ae84e5c6ccfc7acd/docs/docs/create-source-plugin.md#adding-relationships-between-nodes

**Comment by datakurre** [comment]
@KyleAMathews Thanks. Those terms did confuse us indeed, because we were using term like tree parents and children to map content hierarchy. Apparently there is no way to map 1:n relationships then.

Good thing is that We probably don’t even need them and our misuse of parent/children probably lead to huge graphql results we can now fix...

@calcsam I suggest you update to docs so that parent / children should not be used to map relations in content hierarchy (just dependencies), also updates (createNode) update children and that they are really just for transformer plugins :)

**Comment by datakurre** [comment]
@cekk removal of parent/children will break all the current uses; I fix examples here and provide pull for starter when I’m ready

@ajayns You may continue your GSOC with the current version, because there may not be enough time in GSOC for you to fix and adapt examples for this

**Comment by pieh** [comment]
> Apparently there is no way to map 1:n relationships then.

The `___NODE` convention allow to set either single node id (for 1:1) or array of node ids (for 1:N)
