### ISSUE TITLE
GSOC 2018 final report for evaluation

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-source-plone#138]
GSOC requires a final report from student. That's a single document that should contain pointers for all code produced by student. It should also be pretty persistent.

I'd propose that @ajayns sets up a dummy blogger blog with a single post that would be a composition of all his weekly reports, but including only links to those pull requests including his code.

This should not be a problem, because all code has beem merged using pull requests and @ajayns has already collected links to pulls in his weekly reports.

**Comment by datakurre** [comment]
https://developers.google.com/open-source/gsoc/help/work-product

**Comment by ajayns** [comment]
@datakurre Yes, I read about this and I've been maintaining all my weekly reports in this document: https://docs.google.com/document/d/1x4CkE8jwxrJvgTIiCRrtRaPIttuuTZE6HmckgrzLMpQ/edit?usp=sharing

I'll just need to add links to the initial PRs cause I wasn't following that pattern initially. Any other things that I'll need to add to this doc? Am I missing something or is there anything to be improved?

**Comment by ajayns** [comment]
A blog as such I hadn't thought of it, my plan was to write a summary style article on my existing Medium blog about my experience on working on this project for GSoC, what it's about and what exactly has been developed.

**Comment by ajayns** [comment]
Since I'm planning to write a detailed report of my GSoC experience after final evaluation, would the Google doc suffice for now? Also as a final report detailing on all the work and features done, would it be a good idea to have a single page document added to this repo itself? Cause then it could maybe be used as documentation on the features it has, what do you think about that idea? 
What I'm thinking is, right now I'll do this and later, after final evaluation I'll do a writeup in detail on my Medium blog! 

Opinions @cekk @datakurre 
Further, I'll read up on the past years GSoC requirements so I can have a better idea and plan

**Comment by datakurre** [comment]
@ajayns I'd prefer that the final report for the final evaluation is something that only you control (not this repo), public and stable (not something we could remove).

According to https://developers.google.com/open-source/gsoc/help/work-product a public Google document should be ok. The first example also mentions GitHub gist:

"""
Create a blog post or web page or public GitHub gist that describes the work you've done and links to the commits you've made and repositories you've worked on. If there is still work to be done on the project, include that too. You can also share highlights or challenging pieces.

    ❗ This is the best option because it allows you to easily include a lot of information. This is good because it will clearly show what work you did, as well as make it easy for others to use and understand your code.
"""

**Comment by ajayns** [comment]
I'm planning on moving forward with the gist idea: https://gist.github.com/ajayns/ab620303bd605e89579b548aac858f19 

A single md file compiling all of the weekly reports and final conclusion of the project would do yes? @cekk @datakurre

**Comment by datakurre** [comment]
@ajayns Maybe, in the final report, instead of concatenating weekly report, provide a short introduction with 

"""
a short description of what work was done, what code got merged, what code didn't get merged, and what's left to do.
"""

and the a chronological list of all you pull request in syntax of "link, description".

Please, make sure to only include your own pull request, not the ones containing only my code. (If I have made some random commits into your pull requests, that should not matter.)

Also, maybe the links should lead directly to diff view of pull request https://github.com/collective/gatsby-source-plone/pull/31/files

I'm ok with including also weekly reports in the gist in different file.

**Comment by ajayns** [comment]
Will do! Thanks for the suggestions!

**Comment by cekk** [comment]
+1 with everything

**Comment by ajayns** [comment]
Once I'm done with the narrative docs, I plan to finish this part up as soon as possible, give you guys time to review (over the weekend) and give final submission before the deadline. Does this sound good? Already discussed with @cekk , @datakurre opinions?

**Comment by ajayns** [comment]
Hey guys, I've tried splitting the content into two files. One for the final report and another the weekly briefings. @datakurre @cekk Any suggestions on rearranging content or anything I may have missed out would be appreciated! This is not final, I'm still working doing a few reviews.

**Comment by datakurre** [comment]
@ajayns Only one. Try adding subheading "Get the code" before the links in "Plone GatsbyJS Integration". That's because GSOC visitors will get to the page by clicking the link "Get the code" from GSOC project listing.

**Comment by cekk** [comment]
It seems ok.
There are all required informations and links.
Specific documentation is in the repos.
All pr are linked and your contribution is easily recognizable.

@datakurre from your experience, is it ok or needs some additional infos?

**Comment by datakurre** [comment]
I believe it is ok. At least it is far better than most I have seen on previous GSOC pages.

**Comment by ajayns** [comment]
Okay that sounds great! How about I do a full review tomorrow once again and make the submission?

**Comment by ajayns** [comment]
I didn't find anything much that required a major change. Shall I move forward with the submissions?
@cekk @datakurre

**Comment by datakurre** [comment]
@ajayns Maybe to write the introduction in past tense?

I think, it is a great report.

**Comment by ajayns** [comment]
Ahh, I missed that! Very good advise there, I've redone the description, let's get a final review and submit. @datakurre @cekk

**Comment by cekk** [comment]
green light

**Comment by ajayns** [comment]
Great, I'll submit it now!

**Comment by ajayns** [comment]
Update: I've submitted! Unsure if you guys can see it now already, but if can, do check it out. I went through everything once again and all looks good. Thanks guys for the guidance! @cekk @datakurre

**Comment by cekk** [comment]
thank you for the amazing work!
