### ISSUE TITLE
make build command giving error .

### ISSUE THREAD

**Issue by iFlameing** [collective/gatsby-source-plone#158]
I am trying to get started with this project I clone this  project and run the make build command. It gives me error 

 TypeError: Cannot read property 'allPloneCollection' of undefined
  
  - gatsby-node.js:52 Object.exports.createPages
    /home/iflameing/Documents/Github/gatsby-source-plone/tests/gatsby-starter-de    fault/gatsby-node.js:52:19

**Comment by datakurre** [comment]
That is should mean that your site has no collections yet and you should remove collection query to get build pass.

This is more general gatsbyjs issue, probably not yet fixed.

**Comment by datakurre** [comment]
Related https://github.com/collective/gatsby-source-plone/issues/135 but actually gatsbyjs is working for generic solution.

**Comment by iFlameing** [comment]
when I am removing the query then it giving me another error when I am running  command make build

   1 |
>  2 |   fragment Event on PloneEvent {
     |                     ^
   3 |     id
   4 |     title
   5 |     description
   6 |     start(formatString: "MMMM Do, YYYY @ HH:MM")
   7 |     text {
   8 |       react
   9 |     }
  10 |     _path
  11 |   }

**Comment by iFlameing** [comment]
@datakurre I also don't find any communication channel link . sorry for this question if I miss something in docs.

**Comment by iFlameing** [comment]
@datakurre I remove all the the query from the test directory but still getting this error :(


 GraphQLCompilerContext: Unknown document `Document`.


  Error: Invariant Violation: GraphQLCompilerContext: Unknown document `Document`.
  
  - invariant.js:42 invariant
    [gatsby-starter-default]/[fbjs]/lib/invariant.js:42:15
  
  - GraphQLCompilerContext.js:145 GraphQLCompilerContext._get
    [gatsby-starter-default]/[relay-compiler]/lib/GraphQLCompilerContext.js:145:34
  
  - GraphQLCompilerContext.js:116 GraphQLCompilerContext.getFragment
    [gatsby-starter-default]/[relay-compiler]/lib/GraphQLCompilerContext.js:116:21
  
  - filterContextForNode.js:29 Object.FragmentSpread
    [gatsby-starter-default]/[relay-compiler]/lib/filterContextForNode.js:29:32
  
  - GraphQLIRVisitor.js:35 visitIR
    [gatsby-starter-default]/[relay-compiler]/lib/GraphQLIRVisitor.js:35:10
  
  - filterContextForNode.js:36 filterContextForNode
    [gatsby-starter-default]/[relay-compiler]/lib/filterContextForNode.js:36:5
  
  - query-compiler.js:182 compilerContext.documents.forEach.node
    [gatsby-starter-default]/[gatsby]/dist/internal-plugins/query-runner/query-compiler.js:182:54
  
  - Array.forEach
  
  - query-compiler.js:169 
    [gatsby-starter-default]/[gatsby]/dist/internal-plugins/query-runner/query-compiler.js:169:35
  
  - Generator.next
  
  - debuggability.js:313 Promise._execute
    [gatsby-starter-default]/[bluebird]/js/release/debuggability.js:313:9
  
  - promise.js:483 Promise._resolveFromExecutor
    [gatsby-starter-default]/[bluebird]/js/release/promise.js:483:18
  
  - promise.js:79 new Promise
    [gatsby-starter-default]/[bluebird]/js/release/promise.js:79:10
  
  - query-compiler.js:199 Runner.write
    [gatsby-starter-default]/[gatsby]/dist/internal-plugins/query-runner/query-compiler.js:199:7
  
  - query-compiler.js:81 
    [gatsby-starter-default]/[gatsby]/dist/internal-plugins/query-runner/query-compiler.js:81:26
  
  - Generator.next
  

Makefile:81: recipe for target 'public' failed
make[1]: *** [public] Error 1
make[1]: Leaving directory '/home/iflameing/Documents/Github/gatsby-source-plone/tests/gatsby-starter-default'
Makefile:59: recipe for target 'build' fail

**Comment by iFlameing** [comment]
@datakurre I resolved the above issue but it is now giving me error 

Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

   5 | const Document = ({ data, images = [], files = [] }) => (
   6 |   <article>
>  7 |     <h1>{data.title}</h1>
     |               ^
   8 |     {data.description ? (
   9 |       <p>
  10 |         <strong>{data.description}</strong>


  WebpackError: TypeError: Cannot read property 'title' of null
  
  - Document.js:7 Document
    lib/src/components/Document.js:7:15
  
  - bootstrap:15 d

**Comment by iFlameing** [comment]
@datakurre any help regarding this issue ?

**Comment by datakurre** [comment]
I’m sorry, but it’s weekend :)

1) Try cloning gatsby-starter-plone instead; it has simpler setup than the source plugin itself, by purpose

2) Read GatsbyJS tutorial. After the plugin has fetched data from a Plone site, everything is just as in any GatsbyJS project. Eg. learn to use its GraphiQL interface (advertised when running gatsby develop) to learn the queries and what’s available from your Plone site

**Comment by ajayns** [comment]
Sorry I'm caught up something as well at the moment. But yes, seems like what @datakurre suggested would help. Once you get a hang of GraphiQL and how everything fits together in Gatsby you should be able to resolve this. And yes, gatsby-starter-plone has a fairly easy setup to get started quick. Do check it out and let us know how it goes.

**Comment by iFlameing** [comment]
@ajayns I built the gatsby-starter-plone successfully . How I can get started with it ?

**Comment by datakurre** [comment]
I didn’t realise originally that you were trying to build test site in gatsby-source-plone. It expect certain Plone pages to be available so these error were
probably related to that (eg. if GraphQl query for index page failed? because it did not exist, “data” would have been null).

About starter. After building the starter, change baseUrl in gatsby config to point to your site.

**Comment by iFlameing** [comment]
@datakurre @ajayns  when I am pointing to my plone website it giving me 
  Error: Request failed with status code 404
I tried a lot but didn't find any solution . @datakurre I don't want to ruin your  weekend you can get this issue on tomorrow also.

**Comment by iFlameing** [comment]
I think I am not able to setup my plone website correctly don't no why. If I have to do something on my localhost  website .

**Comment by datakurre** [comment]
You need to have plone.restapi installed on your Plone site.

**Comment by iFlameing** [comment]
I follow the tutorial of the docs and when I query the 
{
  allPloneDocument {
    edges {
      node {
        _path
      }
    }
  }
}


I get following output 

{
  "data": {
    "allPloneDocument": {
      "edges": [
        {
          "node": {
            "_path": "/front-page/"
          }
        }
      ]
    }
  }
}


I am confused now because Plone websiter working with tutorial but not with the repositories .

**Comment by datakurre** [comment]
That sounds correct. You are querying for Document type nodes and the default new Plone site has only front-page, and a few folders and collections.

**Comment by iFlameing** [comment]
@datakurre I found that why it is giving me allplonecollection of undefined because when I am querying 

query IndexPageQuery {
  ploneDocument(_path: { eq: "/frontpage/" }) {
    title
    description
  }
}

it giving me 

{
  "data": {
    "ploneDocument": null
  }
}

How I can add data to my plone website so that this query return something

**Comment by iFlameing** [comment]
@datakurre the following error occur due to I am not able to query 

  allPloneEvent {
    edges {
      node {
        _path
      }
    }
  }

and 

      allPloneNewsItem {
        edges {
          node {
            _path
          }
        }
      }

they are giving 

{
  "errors": [
    {
      "message": "Cannot query field \"allPloneEvent\" on type \"Query\". Did you mean \"allPloneSite\", \"allPloneFile\", \"allPloneDocument\", \"allPloneImage\", or \"allPloneFolder\"?",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}

How to resolve this any suggestions ?

**Comment by iFlameing** [comment]
@datakurre since I am not passing token in gatsby.config.js I am not able to query  allPloneEvent and allPloneNews but now I am able to query all the query present in the [gatsby.node.js](https://github.com/collective/gatsby-source-plone/blob/master/tests/gatsby-starter-default/gatsby-node.js) but still I am getting error when I am trying to build the gatsby-source-plone by command make build .

TypeError: Cannot read property 'allPloneCollection' of undefined
  
  - gatsby-node.js:37 Object.exports.createPages
    /home/iflameing/Documents/Github/gatsby-source-plone/tests/gatsby-starter-de    fault/gatsby-node.js:37:19

is I still missing something? :(

**Comment by datakurre** [comment]
Yes, there are still queries for collections in your code. But, you could also add a public collection to your Plone site :)

**Comment by datakurre** [comment]
This is becoming guessing, but it sounds like your build failed to transform images from the site and that’s why “fixed” attribute on image node is missing. I cannot guess the reason for that but there might be other errors visible earlier.

I know that the plugin can currently only fetch public images (it does not yet use token for fetching the images as it should).

**Comment by iFlameing** [comment]
@datakurre How I can resolve this ? I hope this is the last issue I am facing :)

**Comment by datakurre** [comment]
That sounds like issue in the example code of the starter. templates/default.js is receiving something unexpected and passing null value for the layout component and it cannot handle that. In the case that you are doing everything else right, the easiest way to get forward is probably to tweak the layout component code to survive if the value of children is null.

**Comment by iFlameing** [comment]
@datakurre I tweak layout component now another error comes of null, I think that problem is something different somehow data which is fetch by graphql is not reaching to our component . How I can debug this any suggestions or can you provide me proper steps to build the project.

**Comment by datakurre** [comment]
I’m sorry, but I don’t know the data of your Plone site.

Since you already built gatsby-starter-plone successfully, maybe you should probably go back there and go trough GatsbyJS tutorial with that at first.

gatsby-source-plone just fetches and prepares a lot of JSON from a Plone site for GatsbyJS offer with GraphQL to use as data in ReactJS components. GatsbyJS documentation walk throught that nicely and also tells how to use GraphiQL to debug.

**Comment by iFlameing** [comment]
@datakurre finally I build the project after tweaking some code in component folder not to much but just handling the null case :)  thank you very much for answering my doubts. I am doing some mistake in building the local plone site and it take some days to familiar with the plone. Now How I can contribute to this project ?I learned a lot of things during the building process.

**Comment by iFlameing** [comment]
@datakurre  can you assign me a starter issue ?

**Comment by datakurre** [comment]
@iFlameing I believe we are missing good issues here. Yet, the issue of private images not working because  the token is not passed to the image download could be a one.

**Comment by iFlameing** [comment]
@datakurre  ok I will open a issue regarding this issue and try to solve it. Any starter tips regarding this issue because I am new to plone website and I faced lot of problem in setting up my local plone site. should I close this issue because I think that it is resolved ?. Thank you very much regarding this issue :)

**Comment by iFlameing** [comment]
@datakurre is this project coming gsoc 2019 or not can you tell me because I am participating in it ?

**Comment by datakurre** [comment]
I don’t know if it is included in the official “ideas list” for Plone Foundation, but sure the rules allow submitting proposal for any good idea.
