### ISSUE TITLE
Why is Babel compilation for gatsby-node.js setup?

### ISSUE THREAD

**Issue by ajayns** [collective/gatsby-source-plone#16]
When the plugin is added to gatsby, doesn't it compile by itself then? Why do we need to separately configure this, when I assume gatsby should be doing it automatically? So is that absolutely necessary? 

@tisto

**Comment by datakurre** [comment]
@ajayns What was the resolution of this? My assumption was that Gatsby cannot compile 3rd party plugin in node_modules but the plugin must be compiled before published to npm.

**Comment by ajayns** [comment]
Yes! @datakurre
