### ISSUE TITLE
Permission to collective/gatsby-source-plone.git denied to vinay72.

### ISSUE THREAD

**Issue by vinay72** [collective/gatsby-source-plone#163]
When I try to push my new branch to this repository after forking it , error is showing in my terminal. Please give me access rights for doing this.  Here is the preview : 
![screenshot from 2019-01-30 17-11-32](https://user-images.githubusercontent.com/28500944/51979113-43b19180-24b2-11e9-989b-6f7cc78dd413.png)

**Comment by datakurre** [comment]
You should clone the repo into your personal GitHub area, push the branch there and create pull request from there.

**Comment by vinay72** [comment]
Thanks for replying.
