### ISSUE TITLE
Use npm link/yarn link for plugin testing

### ISSUE THREAD

**Issue by ajayns** [collective/gatsby-source-plone#17]
Currently in the gatsby-default-starter used for testing, we use the **gatsby-source-plone** plugin by downloading it from the Github [repos](https://github.com/collective/gatsby-source-plone/blob/a39aaa0f274fce3e79dec11ec3ae0a1aff927e15/tests/gatsby-starter-default/package.json#L10). So when any changes are made locally, it cannot be directly tested in the starter.

I've been working on and reading about building and managing npm modules and I came across [yarn link](https://yarnpkg.com/lang/en/docs/cli/link/) which could really help us here in real time testing of the module as changes are made. 

Opinions @tisto @cekk @datakurre

**Comment by cekk** [comment]
why not?

**Comment by ajayns** [comment]
@cekk What I meant was why don't we make this the default method for testing and add it to the docs...

**Comment by cekk** [comment]
yeah, my comment was an "ok".

I once used npm-link for a project and it was useful, so yarn link for tests could be a good idea.

<paranoic-mode>check if it works well also on travis, for the CI</paranoic-mode>

**Comment by ajayns** [comment]
We're already using `yarn link` for CI I believe: https://github.com/collective/gatsby-source-plone/blob/a39aaa0f274fce3e79dec11ec3ae0a1aff927e15/.travis.yml#L26
