### ISSUE TITLE
GSOC 2019 Project planning

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-source-plone#171]
GSOC 2019 Project planning at https://github.com/collective/gatsby-source-plone/projects/2

Checklist

* [ ] how to use project board (everything into backlog first, scheduled tasks get moved into todo, not everything need to be an issue, board is to make all work visible)

* [ ] initial tasks from the project proposal

* [ ] ...

**Comment by datakurre** [comment]
@iFlameing Congratulations! https://summerofcode.withgoogle.com/projects/#6126087203979264

Try to get into https://plone.slack.com/ so we can create a channel there and plan asynchronously during the May.

Your primary priority before the coding period is to finish all study and other work so that you can focus the coding period on this project accordingly (40h / week expected).

If you have time for preparing, try to get https://github.com/collective/gatsby-source-plone/ development environment running by following the docs and file an issue if something is broken.

The plugin code has ES7 async generator all around so prepare to spend some time to get familiar with how the code is executed. The reason for that is to avoid ever needing to have all the nodes in memory of the plugin at the same time, but be able to build one node at time.

I'll try to get you a Plone Docker image with websocket based change notifications before or very early in the coding period so that you'll save from not needing to implement that mock server.

**Comment by iFlameing** [comment]
@datakurre I don't have an @plone.org email address. can you send me an invitation?

**Comment by datakurre** [comment]
@iFlameing Oh, I forgot that. Let’s wait for a few days if Cris has time to invite everyone there and if not, then we can go to Gitter.im. Last year everyone used Slack, but this year I expect that at least some projects are already at Gitter... I don’t have strong opinion, but would just like to follow the community :)

**Comment by datakurre** [comment]
@iFlameing Gitter.im be it. Also Plone channels there are more active than Slack ones nowdays https://gitter.im/collective/gatsby-source-plone

**Comment by datakurre** [comment]
Good enough.
