### ISSUE TITLE
Introductory post

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-source-plone#172]
Please, write an introductory post to community.plone.org describing shortly

- your background
- why did you want to apply to GSOC
- your project
- what kind of feedback would you like to get from the community

**Comment by iFlameing** [comment]
ok!

**Comment by iFlameing** [comment]
@datakurre I created a topic related to my introduction with all the above question at [plone.community.org](https://community.plone.org). Please! take a look and suggest me any changes if needed :)
https://community.plone.org/t/introduction-alok-kumar-iflameing/8535
