### ISSUE TITLE
Writing test for Fetch-private-image

### ISSUE THREAD

**Issue by iFlameing** [collective/gatsby-source-plone#175]

**Comment by iFlameing** [comment]
@datakurre we are currently testing utils function only. How we can test the gatsby-node.js function creatRemoteFileNode function.

**Comment by datakurre** [comment]
@iFlameing I don’t know. Last year, when wrote this plugin, there was no good examples available in other plugins either. That’s why we are testing the resulting test site with Robot Framework (I recall that other plugins were testing react component renderings for the result).

For me it is ok that you try to refactor your code into utility functions and test those (similarly or better than utils.js).

**Comment by iFlameing** [comment]
@datakurre gatsby-source-filesystem already written test for all its options, and httpHeaders are one of them so I think that it is irrelevant to test the httpHeaders feature by yourself. pieh already wrote a test for httpHeaders in gatsby-source-filesystem https://github.com/gatsbyjs/gatsby/pull/11682/commits/f2179e89f72653c46d632f3df22ebd12dd44faf8
should we close this issue? what do you think?

**Comment by datakurre** [comment]
Agreed.
