### ISSUE TITLE
Shift from buildout to Docker for running plone restapi

### ISSUE THREAD

**Issue by ajayns** [collective/gatsby-source-plone#18]
Currently, the project locally builds Plone to be used as backend, rather than this, we can just add documentation for installing docker, pulling the [plone.restapi](https://hub.docker.com/r/kitconcept/plone.restapi/) from docker hub and running it locally for development.

**Comment by ajayns** [comment]
@cekk @datakurre @tisto

**Comment by cekk** [comment]
I like the idea about using Docker, but i don't know if is a good idea totally replace buildout approach.
Could be a good idea let developers choose their destiny? Running a buildout or running a docker image, and explain how in the README.

Is it easy to setup a docker image in a Makefile like we do with the buildout?

@tisto @datakurre what do you think?

**Comment by datakurre** [comment]
I would support replacing Buildout with docker in this project, because this should be usable without Buildout or Python knowledge.

@tisto @sneridagh Does kitconcept/plone.restapi Docker image already have CORSPolicy configured? Like in https://github.com/collective/gatsby-source-plone/blob/master/api/buildout.cfg#L20

**Comment by ajayns** [comment]
@datakurre I'm not sure, but I believe it has cause I've setup a local running instance of Plone with Docker and tested it, seems to work fine with the plugin.

**Comment by sneridagh** [comment]
It does, however only for ports 4300 and 3000. I can add support for Gatsby port as well…
Cheers,
V.

**Comment by sneridagh** [comment]
Now it does:
https://hub.docker.com/r/kitconcept/plone.restapi/tags/

Check brand new 2.0.0 version :)

**Comment by datakurre** [comment]
It’s not yet officially supported installation method, so there is not one. I use buildout.requirements buildout-extension.

**Comment by sneridagh** [comment]
Yes, it's updated, CORS should work for port 8000 as well.

**Comment by ajayns** [comment]
How do I get started so? I'll move from buildout to docker fully and try make a PR?

/cc @sneridagh @datakurre @cekk

**Comment by tisto** [comment]
You can stick with buildout or move to Docker. Whatever makes sense to you. Making Docker the default option for gatsby-Source-plone would make sense to me. 

Von meinem iPhone gesendet

**Comment by datakurre** [comment]
@ajayns I'd say you could completely replace buildout based backend to keep the repository simple. Those how need it, know how to create it.

* [ ] replace ./api with working docker-compose.yml
* [ ] remove build-backend an build-test -targets from Makefile
* [ ] update README with instructions to start backend with ``docker-compose up``

**Comment by ajayns** [comment]
Where can I find example or guide on creating the `docker-compose.yml` file? 

I thought the commands to be added to the Make file or readme were:
```
// To pull docker image
docker pull kitconcept/plone.restapi

// To run it
docker run --rm -it -p 8080:8080 kitconcept/plone.restapi:latest
```
How do I get this to happen via `docker-compose.yml`?

@datakurre

**Comment by datakurre** [comment]
Summary from our slack discussion:

```
$ cat docker-compose.yml
version: '3'
services:
  api:
    image: "kitconcept/plone.restapi"
$ docker-compose up
```

**Comment by ajayns** [comment]
I believe this issue can be closed now. ref: #25
