### ISSUE TITLE
When page is deleted at Plone site, delete node and update affected parent node

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-source-plone#184]
Implement

* [ ] delete main plone node with the same id
* [ ] delete breadcrumbs node for the id
* [ ] delete navigation node for the id
* [ ] update parent node
* [ ] update parent node's navigation node

Research

* [ ] confirm from GraphiQL console that once File or Image node has been deleted, also its related RemoteFileNode is deleted and does not need to be deleted separately (this should work like this, because files are attached as "children" of their owning PloneNodes)

**Comment by iFlameing** [comment]
resolved in #189

**Comment by datakurre** [comment]
@iFlameing Did you check that when you remove an Image page from Plone, also its associate "remote file node" is deleted?

**Comment by iFlameing** [comment]
@datakurre No, I only tested deleting a folder and its children. Going to test it out. sorry!

**Comment by datakurre** [comment]
@iFlameing No worries! Thanks already for testing that for me.

**Comment by iFlameing** [comment]
@datakurre I run the query for an individual news item. Before and after deleting the image. I found that when we are adding the image a remote-file-node is attached to the image field and when we deleting the image, image field is assigned with a null value. is this sufficient for checking if remote-file-node is deleted or not? I also try to find the remote file node with getNode(id) but I didn't find any child.

**Comment by datakurre** [comment]
@iFlameing Did you also try the GraphiQL console? I recall that remote file noses were searchable also separately.

But no need to put much more effort to this. It sounds like everything indicates that the file nodes are cleaned up with their parents.

**Comment by iFlameing** [comment]
> @iFlameing Did you also try the GraphiQL console? I recall that remote file noses were searchable also separately.
> 

@datakurre yes! I ran the query at graphiql console.

**Comment by datakurre** [comment]
Thanks! Let’s then consider this done.
