### ISSUE TITLE
Setup gatsby-starter-plone

### ISSUE THREAD

**Issue by ajayns** [collective/gatsby-source-plone#19]
We're using gatsby-starter-default for testing, but since according to my proposal I'll be working making it a full example, wouldn't it be a good idea to start it up now by:

* Updating the starter to use the latest versions of modules (ex: Gatsby)
* Rename it to gatsby-starter-plone

**Comment by datakurre** [comment]
@ajayns Have you been able to think about this? I assume the current test project should work pretty well as a standalone repository with yarn link.

**Comment by ajayns** [comment]
Okay so since, we're not having much issues right now, I think we're good to move on to the starter. So moving step by step, I think the following has to be done first:
* Clone gatsby starter
* Setup Prettier
* Add gatsby-source-plone and basic working

If anything else in particular that needs to be done and I missed, do mention. I'm also looking for other starters to take as reference

**Comment by datakurre** [comment]
Yes. Our current test project is based on gatsby starter, so you could copy stuff from there.

**Comment by ajayns** [comment]
I'll need to create a new repo for this yes?

**Comment by datakurre** [comment]
@ajayns I assume that's the current practice for starters.

**Comment by cekk** [comment]
Yep

**Comment by ajayns** [comment]
https://github.com/collective/gatsby-starter-plone I've created a new repo here

**Comment by datakurre** [comment]
Has been set up well enough to close this.
