### ISSUE TITLE
WebSocket connection should re-connect when Plone server gets restarted

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-source-plone#203]
Currently stopping and re-starting Plone (e.g. make stop-backend start-backend) disconnects websocket connection and it will never re-connect.

We should research if there is "heartbeat"-option for the websocket connection to keep the connection open / detect disconnection and somehow reconnect.

**Comment by datakurre** [comment]
Alternatively "gatsby develop" should exit completely when websocket gets disconnected for any reason. This allows some monitoring service to restart it immediately.

This is probably the MVP for this issue.

**Comment by iFlameing** [comment]
@datakurre can we solve this problem by this solution https://stackoverflow.com/questions/3780511/reconnection-of-client-when-server-reboots-in-websocket?

**Comment by datakurre** [comment]
@iFlameing Yes, but in addition to reconnection on onClose we need implement heartbeat-functionality and manually disconnect + reconnect if too many heartbeats are left without answer.

https://github.com/websockets/ws/blob/a49a827b4eabb4c720993ee1a0c45b737cc148bb/README.md#how-to-detect-and-close-broken-connections

We need to have "hearbeat", that is gatsby-source-plone should do wsconnection.ping() for e.g. once in every 60. The server will reply with "pong" (wsconnection.on("pong", ...). Usually, if more than two ping are sent without pong being received, the connection should be interpreted broken and reconnection should be made. (These things happen in enterprise environments where firewalls may silently kill long-lasting connections in a way that connection does not properly close. Packages just continue to be sent to nowhere.)

**Comment by datakurre** [comment]
In addition to all that, reconnection should happen in increasing intervals:

If Plone server is being restarted, gatsby-source-plone should not try to reconnect unlimited times / sec, but start with reconnection once per second and then increase the reconnection time with some random amount of seconds until it tries reconnection once per every 60 s:

The first reconnection try is done after 1 second delay after the connection has been lost.

The following reconnections trilas are done after Math.min(60, the previous delay * (2 - Math.random())) so that the delay increases with random intervals until the reconnection is tried once per minute.

**Comment by datakurre** [comment]
So, this ends up being a quite a ticket:

* implement reconnection at ws.onclose
* enhance reconnection to try reconnection with increasing intervals (60s at max)
* implement heartbeat (1 ping in every 30 s and disconnect when no pong has been received for 3 consequent pings)
* make heartbeat interval a configuration option

**Comment by iFlameing** [comment]
@datakurre can I use this library it provides automatically reconnecting when client loose connection.
https://github.com/joewalnes/reconnecting-websocket. It is small in size also. what do you say?

**Comment by datakurre** [comment]
That has not been updated for a while. Could you “vendor” it and then try to enhance it with heartbeat-ping?

**Comment by datakurre** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#Pings_and_Pongs_The_Heartbeat_of_WebSockets

**Comment by datakurre** [comment]
Without heartbeat it is possible that a firewall silently kills the connection without proper disconnect.

**Comment by iFlameing** [comment]
@datakurre I am not using the above library. Just created the pull request by implementing the reconnecting functionality. I am not able to reconnect after I stop the backend and then restarted it. can you review the [pr](https://github.com/collective/gatsby-source-plone/pull/239) once!!!
