### ISSUE TITLE
Node type name clash with gatsby-source-filesystem

### ISSUE THREAD

**Issue by ajayns** [collective/gatsby-source-plone#21]
Currently for node types, we're using the same name as the Plone object types, ex: File, Document, Image etc. gatsby-source-filesystem has reserved the node type `File` for it's processing and so we can't use this. 

Ref Discussion in Gatsby: https://github.com/gatsbyjs/gatsby/issues/5182

A solution would be to prepend something like "plone" before node type names, and so the types would look something like: `ploneDocument`, `ploneFile` and so on.

@cekk @datakurre @tisto Opinions?

**Comment by datakurre** [comment]
Sounds like in that context it should be PloneFile, PloneDocument, etc.

**Comment by ajayns** [comment]
Yeah that sounds good, prepending 'Plone' to the types...

**Comment by ajayns** [comment]
This is resolved with #45
