### ISSUE TITLE
Use prettier for code formatting

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-source-plone#24]
Any reason why we should enforce prettier formatting for any supported code in this project?

* [x] install and add dependencies into packages.json
* [x] add Makefile targets to format the code
* [ ] add instructions how to configure editor to autoformat saved files

I've noticed that once I've got older I'm less and less interested in being "right" in code formatting wars and just adapt to any automated tool there is (prettier, elm-format, yapf, isort, ...)  :)

/cc @ajayns @tisto

**Comment by tisto** [comment]
+1 to prettier.

**Comment by datakurre** [comment]
Fixed in https://github.com/collective/gatsby-source-plone/pull/25
