### ISSUE TITLE
core-js version problem

### ISSUE THREAD

**Issue by Gomez** [collective/gatsby-source-plone#248]
Got this error:

```
Error in "/home/gomez/dev/portknox_gatsby/node_modules/gatsby-source-plone/gatsby-node.js": Cannot find module 'core-js/modules/es6.objec
t.define-property' 
```

Looks like core-js needs to be pinned to `npm install core-js@2.6.11  --save`.

**Comment by datakurre** [comment]
Sounds possible, but also something I would expect to be pinned already in GatsbyJS 🤔

**Comment by Gomez** [comment]
Just found out it was pinned in my project (to "^3.4.7"). Will investigate.

**Comment by Gomez** [comment]
So, it was pulled in by custom gatsby-browser.js. 

Closing as not valid.
