### ISSUE TITLE
Update .gitignore and .npmignore

### ISSUE THREAD

**Issue by ajayns** [collective/gatsby-source-plone#27]
Babel compilation that's setup compiles `gatsby-node.js` in the `/src` directory to root directory. Taking [gatsby-source-wordpress](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-wordpress) as reference, I think it'd be a good idea to add `gatsby-node.js` in the root directory to `.gitignore`, as we don't need it in development.

Also, the size of the package can be reduced while publishing to npm by adding `/docs`, `src`, `tests` and so on in `.npmignore`. I've seen this pattern followed in many npm packages.

Opinions @cekk

**Comment by ajayns** [comment]
@cekk yes! I'll check out a few popular packages and also try to find guidelines to follow while working on npm packages, then get back and confirm what'd be the best way to go.

**Comment by ajayns** [comment]
I see a few packages using the approach I mentioned for their `.npmignore` and `.gitignore`, I think this itself would be in the best practices.

What do you think @datakurre  @tisto 
Do add on if there's anything, else I'll move forward with a PR

**Comment by datakurre** [comment]
Sounds good to me.

**Comment by cekk** [comment]
Merged #28
