### ISSUE TITLE
Recursive approach to tree traversal

### ISSUE THREAD

**Issue by ajayns** [collective/gatsby-source-plone#29]
Even though I've decided the work for Recursive algorithm method of tree traversal for second evaluation period, I felt it's necessary that I do research and learn about them so that development then can go smoothly. 

Any tutorials/examples/articles on this kind of approach for traversal and hierarchy would greatly help! Any tips on getting started with this would also be appreciated.
@datakurre @cekk @polyester

**Comment by ajayns** [comment]
How do we move forward in this implementation? We'll create a branch for @search traversal method and use master branch to start building on recursive strategy? @datakurre @cekk

**Comment by datakurre** [comment]
It must be option. With recursive as the default.

I need to figure out how we test that those give the same results by default.

Recursive is the best default, because it should always find all content.

Search is expected to be needed in production to optimize build time.

**Comment by ajayns** [comment]
Okay so the plugin will have options to switch from @search approach and recursive approach?

**Comment by datakurre** [comment]
Yes. I don’t have strong opinion on the option name or type.

One way would be to have option for search parameters and choose search strategy implicitly if search parameters are set. Not sure if that would be too opaque, though.

**Comment by ajayns** [comment]
What's the reason for us providing both the options to the user? What exactly does search params mean and where can they be helpful? 

I'm asking this as it may seem a bit complex for developing a basic gatsby-site off a Plone site. We'll have to provide these options in the simplest way possible with good docs explaining each option.

**Comment by cekk** [comment]
Search params are all query parameters that the search endpoint accept to filter results.
For example if you want to show in Gatsby only News Items, you could setup the plugin with a query that filters portal_types.
I need to check, but I think that you can basically set the query with all the portal_catalog indexes of plone (see searching with plone ref in official documentation).

I think that these two methods are useful when an user wants to reproduce the entire site (recursive method) or filter the results (@search method).
I'm ok with the opaque method: default is recursive method and if a query is set, then use the search.

**Comment by cekk** [comment]
https://plonerestapi.readthedocs.io/en/latest/searching.html#search

Here there are examples and a link to the main plone docs

**Comment by datakurre** [comment]
@ajayns I agree what Andrea said.

Plone gatsby-site developer should be able to start by only settings baseUrl. Then the plugin would work recursively to make all content available in GraphQL.

Once the site goes to production, it is important to minimize the build time to give editors as fast feedback on their changes as possible. By then a more technical user could look for the used GraphQL queries and configure a such Plone search parameters that would fetch only the required page types (or pages with correct publication workflow state) from Plone.

**Comment by ajayns** [comment]
@cekk @datakurre Oh alright, now it's starting to make way more sense. So I'll add an option to take in search params, which, if not set, defaults to the recursive algorithm.

**Comment by ajayns** [comment]
@cekk @datakurre Anything pending here as well? I believe we can close this issue.

**Comment by datakurre** [comment]
I assume that this is done. I’ll should be able to return to try these out in early July at latest. I’ll open new issues if I find any.
