### ISSUE TITLE
error GraphQL Error Unknown field `allDocument` on type `RootQueryType`

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-source-plone#34]
Suddenly, I'm unable to run build locally. @ajayns did you update example under tests with your changes?

Bigger mystery is, if something is broken, why we were unable to catch this on Travis. I'll investigate.

```
error GraphQL Error Unknown field `allDocument` on type `RootQueryType`

  file: /home/datakurre/Work/gatsby-source-plone/tests/gatsby-starter-default/src/pages/index.js

   1 | 
   2 |   query IndexPageQuery {
>  3 |     allDocument {
     |     ^
   4 |       edges {
   5 |         node {
   6 |           id
   7 |           title
   8 |           description
   9 |         }
  10 |       }
  11 |     }
  12 |   }
  13 | 
```

**Comment by ajayns** [comment]
Oh wow let me check out what's happening, it seemed to have worked fine for me.

**Comment by datakurre** [comment]
Travis seems to still pass so I wonder too :/

**Comment by ajayns** [comment]
@datakurre I cross checked it, it still working fine locally for me. The only reason I could think of is that your Plone site doesn't have any content objects of type `Document`, if that's possible.

**Comment by datakurre** [comment]
@ajayns Thanks for that tip. Once I can confirm that I close this and add the reason to faq / troubleshooting.
