### ISSUE TITLE
Step by step approach with @search traversal

### ISSUE THREAD

**Issue by ajayns** [collective/gatsby-source-plone#48]
I've checked out the current changes @datakurre made, looks like we've gotten the full content objects. But I was thinking of an approach where we split up each task and display logs to the terminal so that the user can get periodic feedback on the progress when he runs `gatsby develop`.

So if we'd want this I'd like to refactor the code the following way:
```javascript
...
// Keeping this helper just to fetch data from URL using axios
const fetchData = async (url, auth) => {
  const { data } = await axios.get(url, {
    headers: {
      accept: "application/json",
    }
  });
  return data;
};

exports.sourceNodes = async ({
  boundActionCreators,
  getNode,
  hasNodeChanged,
  store,
  cache
}, {
  baseUrl,
  auth
}) => {
  const {
    createNode
  } = boundActionCreators;

  console.log("Fetching urls");
  const data = await fetchData(`${baseUrl}/@search`, auth);

  // Fetching data from navigation/breadcrumbs will come here
  console.log("Fetching item data");
  const items = await Promise.all(
    data.items.map(async item => {
      const url = item["@id"];
      const itemDetails = await fetchData(url, auth);
      return itemDetails
    })
  );

  // Tree hierarchy setup will happen here
  console.log("Creating node structure");
  const nodes = items.map(item => {
    let node = {
      ...item,
      internal: {
        type: "Plone" + item["@type"].replace(" ", ""),
        contentDigest: createContentDigest(item)
      }
    };
    node.id = item["@id"];
    node.parent = null;
    node.children = [];

    return node;
  });

  console.log("Creating nodes");
  nodes.map(node => createNode(node));
};
```

As you can see, I've split up each task and logged it into console, so on `gatsby develop` user gets constant feedback. User can recieve feedback on what's failed this way, furthermore we're splitting up functions so that code readability is improved.
Would this be a good idea?  Need your opinions to move forward @cekk @datakurre @polyester @tisto

**Comment by datakurre** [comment]
@ajayns Yes, please, refactor. The full texts was just to try that out.

**Comment by datakurre** [comment]
@ajayns Please, abstract console.log behind a function so that’s easy to disable later (or add logging) levels.

**Comment by ajayns** [comment]
@datakurre By abstraction do you mean a function with a parameter? Something like: 
```javascript
const abstractionFn = (message, dev = false) => {
  dev && console.log(message)
}
```

**Comment by datakurre** [comment]
@ajayns Jes.

**Comment by ajayns** [comment]
Will make the changes, also, this `dev` variable which I've mentioned in the above function, could be passed in through the Gatsby project? Would that be a good idea?

So for instance, in a Gatsby project, user can add `devMode: true` or something similar to the `gatsby-config.js` and it'll start logging everything.  @datakurre

**Comment by cekk** [comment]
You could add a flag in the config, for example "showLogs" or similar.

I was thinking about using standard NODE_ENV variable that is automatically set to production or development, but we could want enable logging also in production mode for debug

**Comment by datakurre** [comment]
@ajayns later you may want to add support for more than just true/false (levels like debug/info/warning), but that design allows you to do that later

**Comment by ajayns** [comment]
Okay cool, I'll note it down for later.

**Comment by datakurre** [comment]
@ajayns After closing this, will you open a new ticket for @search traversal? (Currently only the first page of @search results is processed, @search cannot be parametrized and node parents are not resolved)
