### ISSUE TITLE
Handling authorization options

### ISSUE THREAD

**Issue by ajayns** [collective/gatsby-source-plone#56]
The flow I've outlined for handling authorization would be adding an `auth` object as an option in `gatsby-config.js` which would take in `username` and `password` and hence all the fetch data calls will be made using those auth headers. 

But this `auth` object should be optional and so that means in case it's passed as `undefined` to fetch data, it should make normal calls instead. 

How does this sound? @cekk @datakurre

**Comment by datakurre** [comment]
@ajayns Username and password is a bad idea. Never require user to save password in plain text. We could

* [ ] have a script
* [ ] that prompts user for username and password
* [ ] gets JWT for the user from plone
* [ ] saves username + token into gatsby-config.js

I've used npm package called ``prompt`` once to ask for password in similar purpose. Here I save authentication cookie instead of the password:  https://github.com/datakurre/plonetheme-upload/blob/master/index.js#L88

**Comment by ajayns** [comment]
So a user would initially need to run this script, and then the script does the job of prompting for user/pass and also saves token into `gatsby-config.js`. Once this is done, then the user can work on the plugin like normal?

**Comment by datakurre** [comment]
Yes. Although now there is danger that if the token is saved into ``gatsby-config.js`` user will accidentally commit it into version control.

Maybe the username and token should be saved into a completely separate file, probably located into the project directory (the same directory with gatsby-config.js).

That plonetheme-upload asks username and password, gets the authentication cookie, saves the cookie into ``.plonetheme-upload-cookie`` and uses it as long as there is no HTTP 401 errors.

**Comment by ajayns** [comment]
Okay this is turning out to be a bit more complicated than expected.

**Comment by cekk** [comment]
I'm not convinced too much about the script.
How do and integrator should run the script inside our plugin? Calling it through node_modules/gatsby-source-plone/etc?

Why don't we use env variables?
If you set USERNAME and PASSWORD variables in a .env.* file (gitignored in the project), gatsby on startup will insert them in our env variables and you can access from the plugin and get the token before any other call.
Some references: https://www.gatsbyjs.org/docs/environment-variables/

**Comment by datakurre** [comment]
Guiding user to write down password into file is bad practice.

Instructions to get token with curl has issue of saving password into shell history.

**Comment by datakurre** [comment]
I guss the best option would be that Plone had UI for creating tokens, but that is outside the scope od this project.

**Comment by datakurre** [comment]
Oh, curl can prompt for password. So

* [ ] docs to get JWT from Plone using curl, with curl prompting for password
* [ ] docs to set JWT as env variable as in https://www.gatsbyjs.org/docs/environment-variables/
* [ ] plugin to set Authorization: Bearer {token} header for requests if defined in envs
* [ ] plugin should raise error when Plone reports token expired

**Comment by datakurre** [comment]
except that one was naive... curl can only prompt password for http basic auth

**Comment by datakurre** [comment]
No oneliners with bash :( Script is still possible https://stackoverflow.com/questions/22106028/how-to-use-variables-from-prompt-in-bash-curl-command

**Comment by ajayns** [comment]
Reading through about this, env Variables seem to be the best and recommended solution to handling this. So the only part I didn't properly understand is, are we relying on the user to get JWT and setup the .env? We'll only take care of what happens after that, yes?

**Comment by datakurre** [comment]
Yes. In my opinion we should only support JWT so that we never encourage users to save password anywhere (on computer in plaintext).

Yet, we should provide instructions for users on how safely get JWT. I’ll provide an example for that. It seems that there is no ”oneliner” for that but it requires a couple of commands, run in bash.

**Comment by datakurre** [comment]
Here is a safe way to get Plone REST API authorization token on unix like systems (OSX, Linux, Linux on Windows...):

```bash
bash
read -p "Username: " USERNAME
read -sp "Password: " PASSWORD
curl -s -X POST http://localhost:8080/Plone/@login -H 'Accept: application/json' -H 'Content-Type: application/json' --data-raw '{"login": "'"$USERNAME"'", "password": "'"$PASSWORD"'"}'
exit
```

```bash
# 1. enter a new bash environment 
bash
# 2. read username into environment variable
read -p "Username: " USERNAME
# 3. read password into environment variable without displaying it while typing
read -sp "Password: " PASSWORD
# 4. request authorization token 
curl -s -X POST http://localhost:8080/Plone/@login -H 'Accept: application/json' -H 'Content-Type: application/json' --data-raw '{"login": "'"$USERNAME"'", "password": "'"$PASSWORD"'"}'
# 5. exit bash to forget environment variables
exit
```

These commands should output the token as follows:

```
{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsbmFtZSI6IkpvaG4gRG9lIiwic3ViIjoidXNlcm5hbWUiLCJleHAiOjE1Mjc0NDk0NTl9.epewKm09S6JXe07Ha6UNicN7v9MT32Rrkflxq2OqVRI"
}
```

The value of that token should then be instructed to be saved as env for gatsby.

In gatsby plugin that token should be used (when it is set, plugin should work also without token because REST API on Plone can be configured to be public) by setting header

```
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsbmFtZSI6IkpvaG4gRG9lIiwic3ViIjoidXNlcm5hbWUiLCJleHAiOjE1Mjc0NDk0NTl9.epewKm09S6JXe07Ha6UNicN7v9MT32Rrkflxq2OqVRI
```

**Comment by cekk** [comment]
dumb question: why restapi needs an auth token to expose public data?

**Comment by datakurre** [comment]
plone.restapi defaults to enable REST API only for logged-in users with permission to use the API

**Comment by ajayns** [comment]
@datakurre That looks perfect, will start work on it!

**Comment by datakurre** [comment]
@ajayns Could you please be more specific on what os not working?

**Comment by datakurre** [comment]
@ajayns I’m sorry, but I still didn’t get that what script exactly no longer works?

**Comment by ajayns** [comment]
@datakurre Resolved with a bit of research. I needed to modify the script a bit:
```
#!/bin/bash
read -p "Username: " USERNAME
read -sp "Password: " PASSWORD
curl -s -X POST http://localhost:8080/Plone/@login -H 'Accept: application/json' -H 'Content-Type: application/json' --data-raw '{"login": "'"$USERNAME"'", "password": "'"$PASSWORD"'"}'
exit
```

Also make the file executable with `chmod +x`. And then run the file (`auth.sh`) as `./auth.sh`.

**Comment by ajayns** [comment]
> The value of that token should then be instructed to be saved as env for gatsby.

Does this mean the script has to do this as well?

**Comment by datakurre** [comment]
@ajayns Now I understand. I'm sorry for not being clear about my intentions.

I believe that we should not try to script any of this, but properly document and instruct how to do that manually (how to get token and add it to the file).

Script in gatsby-plugin-plone -repository does not make sense for gatsby-site builders.

It might make sense in "gatsby-plone-starter" if we will have one, but even then it should be documented, how to get the token manually and configure it for the plugin to use.

My example was not intended to be used as a script. It starts with "bash" to also work within "zsh" shells and to not leak secrets after "exit".

**Comment by ajayns** [comment]
@datakurre Oh alright! That makes sense. 
So I'll make a PR excluding the script, but `token` support for the plugin itself and the `gatsby-starter-default`.
