### ISSUE TITLE
Deploy to github pages

### ISSUE THREAD

**Issue by tisto** [collective/gatsby-source-plone#6]
We should deploy the Gatsby output to a github page as a showcase.

**Comment by tulikavijay** [comment]
I would like to work on this, should I just follow this: https://www.gatsbyjs.org/docs/deploy-gatsby/#github-pages. ?

**Comment by tisto** [comment]
@tulikavijay yeah. that sounds like a good start. Though, the question is if this is a good GSoC starting point. You won't learn much about Gatsby or Plone if you work on that task.

**Comment by datakurre** [comment]
@tisto There's now gh-pages branch. Could you give me permissions or enable it for GitHub pages by yourself?

After that, I can configure Travis-CI to update it (from the result from our acceptance tests) after every build on master.

**Comment by datakurre** [comment]
https://github.com/collective/gatsby-source-plone/commits/gh-pages

**Comment by datakurre** [comment]
This works now, but requires for any repo admin (@tisto?) to enable gh-pages feature.

**Comment by tisto** [comment]
gh-pages branch feature is already enabled.

**Comment by datakurre** [comment]
@tisto Is it configured to gh-pages branch? I wonder what’s wrong then :/ gh-pages branch contains gatsby-generated site

**Comment by tisto** [comment]
@datakurre yes it is.

**Comment by datakurre** [comment]
@tisto Can I get admin rights so that I can try to investigate what’s missing?

**Comment by datakurre** [comment]
@tisto Cloned version of the repo works, so it must be something in configration.

**Comment by tisto** [comment]
@datakurre I selected a theme and made you admin...

**Comment by datakurre** [comment]
@tisto Thanks. We have now pipeline for @ajayns to publish plugin MD docs using the plugin developed (MDs are uploaded to Plone and then exported as REST API JSON to be imported again for running tests and creating gh-pages) :)

**Comment by datakurre** [comment]
https://collective.github.io/gatsby-source-plone/
