### ISSUE TITLE
Should we generate PloneSite node for @search-traversed data?

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-source-plone#60]
@ajayns 

For use case of rendering a page tree with Gatsby, how should one get the pages at site root?

I believe we could query for every type of nodes without parents, and assume those being at root (because they don’t have parents).

But would it be easier if we generate one PloneSite node that would have all those as its children? That should also preserve item order from Plone site hand have some other metadata.

Actually, we would get that with the recursive traversal free as in fixture export https://github.com/collective/gatsby-source-plone/blob/master/tests/gatsby-starter-default/fixture/.index.json

So, should we generate one for @@search -traversal?

**Comment by ajayns** [comment]
I believe that'd be a good idea. Currently, for items at root, I guess `parent` ID is assigned but it's pointing to no Node at all, cause Plone site is not currently generated. 

@datakurre So let's move forward with this? We'll just need to create a Node specifically for the root using baseURL.

**Comment by datakurre** [comment]
@ajayns Yes, so with search endpoint it would probably require one extra GET for the baseUrl and add the to the items before setting parent / child relations.

**Comment by datakurre** [comment]
Fixed in #64
