### ISSUE TITLE
Parameters for @search traversal 

### ISSUE THREAD

**Issue by ajayns** [collective/gatsby-source-plone#62]
Opened as suggested by @datakurre  (ref: #48 )
I didn't fully get, what issues are we talking about. For subtree site, isn't it possible to just give the baseURL differently so that we get all the content inside that subsite? So isn't documentation enough for this case?

**Comment by datakurre** [comment]
Yes, the question is, do we need options to limit search with additional parameters. And if we do, what is the syntax for it in gatsby-config.

We should not decide this now, but only when we have tried the plugin with real data. Initially I was not aware how graphql really works with gatsby. Now I know that all limitations could be done with graphql only. Yet parameterizing search to fetch less raw dats from Plone could speed up builds. But we don’t know yet, if that’s a real problem.

**Comment by cekk** [comment]
i agree.
First of all we need to have a plugin that fetches all the data correctly.
I'll let filtering things in the static site when we build the pages with graphql queries.

And later, when the project is in a good shape and we've time for some improvements, we could also add fetching filters in gatsby-config.

**Comment by ajayns** [comment]
Oh, I understand now @datakurre. I've noticed Gatsby does start taking a while for fetching data when there's a lot of content, and this might prove helpful in improving efficiency later on.
And yes, I totally agree with @cekk, it'd be a good idea keep this for a bit later.

**Comment by ajayns** [comment]
@cekk @datakurre If you check the codebase now, we have the searchParams variable to handle search parameters but I'm unsure how to pass them to the plugin and use them. Any pointers on that? The simplest approach I thought of was a string that would be appended to the fetch all items request to @search

**Comment by datakurre** [comment]
I believe searchParams would be an object.

Each key-value pair in thst object should be appended to search url querystring as ?key1=value&key2=value2

If value is list, it should be added once for every value in list as ?key1=value1a&key1=value1b

**Comment by datakurre** [comment]
Yes, it is allowed to have the same key multiple times in querystring, and plone.restapi relies on that.

**Comment by ajayns** [comment]
Hmm okay, I'll come up with a method to handle that!

**Comment by ajayns** [comment]
Is there any sample search parameter I could test this with though? Like anything that's gonna be commonly used perhaps? @cekk @datakurre

**Comment by datakurre** [comment]
review_state=published should show all pages from the test data while review_state=private should show none and result in build error

I don’t know yet, how we could test both search and traverse with the current setup. Maybe gatsby v2 has easy way write tests for plugin.

**Comment by ajayns** [comment]
Can this issue be closed now? We've added docs and the feature is working!

**Comment by datakurre** [comment]
Yes.
