### ISSUE TITLE
Documentation for tree-hierarchy

### ISSUE THREAD

**Issue by ajayns** [collective/gatsby-source-plone#65]
I was thinking we'll add a bit of documentation explaining what this is and also an example use case maybe from our `tests/gatsby-starter-default`

Opinions @cekk @datakurre

**Comment by datakurre** [comment]
@ajayns FYI. I've been following this for replicating Plone page hierarchy in gatsby https://www.gatsbyjs.org/tutorial/part-seven/

**Comment by ajayns** [comment]
Can this issue be closed?
