### ISSUE TITLE
Query not executed in templates warning 

### ISSUE THREAD

**Issue by ajayns** [collective/gatsby-source-plone#66]
While running `gatsby develop` I encounter this on the terminal:
```
warning The GraphQL query in the non-page component "/home/ajayns/Projects/Plone/gatsby-starter-default/src/templates/page.js" will not be run.
Queries are only executed for Page or Layout components. Instead of a query,
co-locate a GraphQL fragment and compose that fragment into the query (or other
fragment) of the top-level page or layout that renders this component. For more
info on fragments and composition see: http://graphql.org/learn/queries/#fragments
```

Maybe we need to refactor our components/pages a bit?

**Comment by datakurre** [comment]
@ajayns there is no such file in current master 😳

**Comment by datakurre** [comment]
Every page but index are currently generated at gatsby-node.js (and with PloneSite also index could be generated)

Every page uses templates/default.js

Templates/default.js renders its contents using type specific component

**Comment by datakurre** [comment]
@ajayns Yes. And if something is not too magical without comments, you may also open issue for me to document it.

if you find something that looks like against gatsby best practices, also open issue about that.

**Comment by ajayns** [comment]
Okay great! Thanks
