### ISSUE TITLE
@search traversal does not resolve pagination

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-source-plone#67]
When there is more than X results (X is maybe 20), search-endpoint will paginate results. That pagination is not currently resolved by the plugin.

**Comment by ajayns** [comment]
Is there any plone site online or do we have fixtures to feed content so that I can check how the endpoints work then and come up with a fix? Or do I have to manually create over 20 items?

**Comment by datakurre** [comment]
you could just copy paste them from existing content in contents view

**Comment by ajayns** [comment]
Yes did that and experimented a bit with the rest.api. Looks like the number of items per page by default is 25. Consulting the rest.api [batching documentation](http://plonerestapi.readthedocs.io/en/latest/batching.html) the approach I'm thinking of is to keep adding item list by making requests until `batching.next` is undefined.
