### ISSUE TITLE
A subsite (folder) as baseUrl returns also the folder at baseUrl

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-source-plone#75]
I tried the plugin for a subsite and got issue with having the folder at baseUrl twice. Once as a PloneFolder and then as a PloneSite.

This is probably a feature of REST API @search endpoint (eventually being a feature from Plone search) that it also returns the folder at the search path itself.

So, possibly content with the exact path of baseUrl should be excluded from created nodes?

**Comment by ajayns** [comment]
Agreed, I'll work on a fix for this.
