### ISSUE TITLE
Update Changelog

### ISSUE THREAD

**Issue by ajayns** [collective/gatsby-source-plone#80]
We've been pushing quite a bit of features and bugfixes, but haven't updated the changelog yet, so I think now would be a good time to do so.

**Comment by datakurre** [comment]
I believe, I have only updated the setup or example, so all features are yours :)

**Comment by datakurre** [comment]
Beyond that I believe that File / Image support is the only one (besides more documentation) blocking a real release.

And before traverse based export?

**Comment by ajayns** [comment]
Yes, File/Image support I've keep it for after the first evaluation, cause I was concerned it may take time and also even more fixing unexpected issues. Also what do you mean by traverse based export?

**Comment by datakurre** [comment]
@ajayns Ok. With traverse based export I mean the recursive export (not using search -endpoint).

Yet, I must admit that search worked better than expected.

**Comment by ajayns** [comment]
Yes! I've already started research on that and thought of an approach. That and handling files would be the main goals for post first-evaluation.

Going through the documentation, do you think any part could do with a bit of improvement? I'm reading through them and making sure, the explanations and examples are good enough to understand what's being conveyed.

**Comment by datakurre** [comment]
@ajayns About documentation. Yes, it would be good to read it through every now and then and make it better in small increments.

**Comment by datakurre** [comment]
This makes no longer sense, since we failed to do early releases for many reasons (and using git+ssh in package.json for starter has been working just fine). changelog will be updated with release. GSOC report will contain detailed description of all the work during GSOC.
