### ISSUE TITLE
Add example and test about use of breadcrumbs expansion 

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-source-plone#82]
We merged REST API expansions support without any tests.

The example already has  breadcrumbs-component, which currently only shows link to the parent of the current page. That should be refactored into displaying full breadcrumbs and a robot test should be written to test that.

**Comment by ajayns** [comment]
I agree, this is an important part of the feature, will commence work, I'm opening a PR for basic docs right now first.

**Comment by ajayns** [comment]
I've been trying to figure out for a while now, but there doesn't seem to be much about it in docs or online. Thing is `@components` has the expansions and all the links to the items in it are in `@id` can properties with special characters be used in GraphQL? Else we'll have to process this data separately I think.

**Comment by datakurre** [comment]
@ajayns I haven't had time to try this out myself yet.

If that data is available, you should be able to query it in grapghiql explorer available with gatsby develop (or make watch).

If that data is not available there, we need to remap all properties starting with `@` with some prefix. If Gatsby allows underscore `_`-prefix  it would be fine. I would be OK also by just removing `@`, but there would be conflict with `@id` and `id`. There `@id` should be just dropped (using it anywhere would most probably just cause issues). `@type` should not cause conflicts, because `type` is reserved name in Python. `@components` might cause conflicts, but I'd expect those to be rare.

@tisto opinions?

**Comment by ajayns** [comment]
I've checked it out in the GraphiQL explorer and then only I noticed these are not available for querying the normal way because special characters support I don't think is there yet for the current GraphQL spec. 

Also yes, I think the way to go would be to remap all the properties with `@` with `_` and that would prevent any conflicts as well. I'm unsure of what approach we can follow for this though cause we currently just spread the data to the node.

**Comment by datakurre** [comment]
Yes, with _ -prefix I meant replacing @ with _.

**Comment by tisto** [comment]
@datakurre I am afraid I need a few pointers to understand the issue.

**Comment by ajayns** [comment]
Content object requests to plone.restapi gives response which has properties including `@components`, `@id`, `@type` and so on. We currently just paste this data directly into Gatsby nodes. So when querying with GraphQL, these properties won't be available, as GraphQL I think doesn't support special characters for its requests.

**Comment by ajayns** [comment]
@datakurre If we're moving forward with, the function that replaces it should be recursive yes? Cause we do not know at level there could be an item with `@id` or so. I've been checking it out and toying around a bit. Are we moving forward this way only?

**Comment by datakurre** [comment]
@ajayns Yes.

I assume you tested that replacing `@` with `_` would make id, type and components visible in GraphQL?

If so, then we should move forward with this.

The data has fixed depth so it could be handled without recursion, but recursive (depth first) function would require least code.

**Comment by ajayns** [comment]
@datakurre I did test it and it seems to be working, that's when I noticed we need it for all properties. Hmmm I'll give it a try let me see.

**Comment by tisto** [comment]
If you need to replace @ with _ on JS level I am ok with that. I wouldn't want to change our API for that. :)

Von meinem iPhone gesendet

**Comment by ajayns** [comment]
I've been trying to get DFS working and it's still only handling the root, any idea where I might be going wrong? Searching online also hasn't been helping much, I'm just getting algorithms.

```javascript
const item = {
  "@components": {
    "breadcrumbs": {
      "@id": "https://plonedemo.kitconcept.com/en/demo/a-folder/@breadcrumbs",
      "items": [
        {
          "@id": "https://plonedemo.kitconcept.com/en/demo",
          "title": "Demo"
        },
        {
          "@id": "https://plonedemo.kitconcept.com/en/demo/a-folder",
          "title": "A Folder"
        }
      ]
    },
    "navigation": {
      "@id": "https://plonedemo.kitconcept.com/en/demo/a-folder/@navigation",
      "items": [
        {
          "@id": "https://plonedemo.kitconcept.com/en",
          "title": "Home"
        },
        {
          "@id": "https://plonedemo.kitconcept.com/en/demo",
          "title": "Demo"
        }
      ]
    },
    "workflow": {
      "@id": "https://plonedemo.kitconcept.com/en/demo/a-folder/@workflow"
    }
  },
  "@id": "https://plonedemo.kitconcept.com/en/demo/a-folder?expand=breadcrumbs%2Cnavigation",
  "@type": "Folder",
  "UID": "2fda50239ba44954b04eb35ff813425e",
  "allow_discussion": null,
  "contributors": [],
  "created": "2015-07-31T15:58:51+02:00",
  "creators": [
    "admin"
  ],
  "description": "",
  "effective": "2015-07-31T15:58:56",
  "exclude_from_nav": false,
  "expires": null,
  "id": "a-folder",
  "is_folderish": true,
  "items": [
    {
      "@id": "https://plonedemo.kitconcept.com/en/demo/a-folder/a-page-inside-a-folder",
      "@type": "Document",
      "description": "Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.",
      "review_state": "published",
      "title": "A Page inside a Folder"
    }
  ],
  "items_total": 1,
  "language": "en",
  "layout": "listing_view",
  "modified": "2018-03-07T10:06:48+00:00",
  "nextPreviousEnabled": false,
  "parent": {
    "@id": "https://plonedemo.kitconcept.com/en/demo",
    "@type": "Folder",
    "description": "Vestibulum dignissim erat id eros mollis vitae tempus leo ultricies. Cras dapibus suscipit consectetur. Integer tincidunt feugiat tristique. Sed et arcu risus. Nam venenatis, tortor ac tincidunt amet.",
    "review_state": "published",
    "title": "Demo"
  },
  "relatedItems": [],
  "review_state": "published",
  "rights": null,
  "subjects": [],
  "title": "A Folder",
  "version": "current"
}


let stack = [item];
let n;
let node = {};

while (stack.length > 0) {
  n = stack.pop();

  Object.entries(n).map(([key, value]) => {
    if (key.startsWith('@')) {
      node['_' + key.slice(1)] = value;
    } else {
      node[key] = value;
    }

    if (value) {
      if ((value.constructor === Array && value.length > 0) || (Object.keys(value).length !== 0 && value.constructor === Object)) {
        stack.push(value);
      }
    }
  });
}

console.log(node);
```

**Comment by datakurre** [comment]
@ajayns I merged the current version, but I’ll look later into why that dfs algorithm didn’t work.
