### ISSUE TITLE
Unit / integration test setup

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-source-plone#92]
We need at least a unit test setup for our plugin (now we only have acceptance testing, limited in building plugin demo site).

@ajayns Please, if you’s get gatsby v2 tests running on your machine. It seems to be using jest + jest-cli for running tests. We could do the same. Some source plugins have tests at `__tests__`-subfolder. I could not find full integration tests, but many had abstracted their helper functions into separate module and tested that (without any gatsby dependencies in test).

**Comment by ajayns** [comment]
Hmm I see, I've seen a  few `__tests__` folders as well. I'll make it first priority to move to gatsby after the search parameters are done with. 

Also, I don't have much experience working with Jest for tests, what would be a good place to get started, thinking in the context of our project and what tests we'd require?

**Comment by datakurre** [comment]
https://facebook.github.io/jest/

**Comment by ajayns** [comment]
I've been going through this and playing around a bit as well. So there seems to be multiple patterns for this implementation. What would be the best for us? Is there anything you'd recommend to look for a reference?

Currently, I was thinking of having a `__tests__` in `/src` and testing each helper function. @datakurre
